### ISSUE TITLE
Случайный переход в сафари к st.yandexadexchange.net

### ISSUE THREAD

**Issue by populius** [yandexmobile/yandex-ads-sdk-ios#1]
Иногда рандомно открывается в сафари линк на st.yandexadexchange.net. На версии 1.9 обычно сопровождалось крашем вебкита 

`*** WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <NSInternalInconsistencyException> NSDictionaryOfVariableBindings failed because either one of the values is nil, or there's something wrong with the way the macro is being invoked.  Cannot assign value nil for key "webView". Keys:(
   webView
)`

на текущей beta1 краша в консоле уже вроде нет, но в сафари кидает

**Comment by kanstantsin** [comment]
Подскажите, в Сафари кидает без тапа по баннеру, т.е. автоматически?
Удалось ли увидеть баннер, который сопровождается крешем или переходом в Сафари?

**Comment by populius** [comment]
кидает без тапа, баннер не увидел. Возможно дело было в каком-то конкретном баннере ибо сейчас проблемы не наблюдаю

**Comment by kanstantsin** [comment]
Спасибо за информацию. Проблему локализовали. Будет исправлена в ближайшее время.

**Comment by populius** [comment]
Спасибо, а не сориентируйте по срокам? и потребуется ли пересобирать билд с новой версией SDK?

**Comment by kanstantsin** [comment]
Проблема исправляется как в SDK, так и на серверной стороне. Рекомендуется обновить SDK до новой версии, в которой данная ситуация будет обрабатываться корректно.
Точные сроки, к сожалению, назвать не могу. Скорее всего в этом году.

**Comment by kanstantsin** [comment]
Исправлено в 2.0.0.
