### ISSUE TITLE
Адапторы не находятся в подсах

### ISSUE THREAD

**Issue by bimawa** [yandexmobile/yandex-ads-sdk-ios#10]
Отловил ошибку, что классов нет, которые хранятся в адаптерах. Они не входят в Подсы? Их отдельно таскать в проект?

**Comment by kanstantsin** [comment]
Да, следуйте инструкциям, описанным в документации
https://tech.yandex.ru/mobile-ads/doc/dg/ios/admob-adapter-docpage/
https://tech.yandex.ru/mobile-ads/doc/dg/ios/mopub-adapter-docpage/

**Comment by bimawa** [comment]
@kanstantsin В этих инструкциях описывается работа со статической библиотекой. Как я понял мы должны использовать динамический фреймворк?

**Comment by kanstantsin** [comment]
Речь про AdMob адаптеры?
Для них, действительно, документация немного устарела.
Актуальные действия:
1. Загрузить статический фреймворк (https://github.com/yandexmobile/yandex-ads-sdk-ios/tree/master/Adapters/AdMob) и добавить его в проект.
2. Добавить путь к фреймворку в Framework Search Paths.

Документация будет обновлена в ближайшее время.

**Comment by bimawa** [comment]
@kanstantsin да спасибо, в роде бы все заработало.
