### ISSUE TITLE
SDK Release 5.0.0 dynamic

### ISSUE THREAD

**Issue by noname1980** [yandexmobile/yandex-ads-sdk-ios#100]
на текущий момент в SDK Release 5.0.0 есть папка static, а в релизе 4.2.2 есть папки и static и dynamic
можете для релиза 5.0.0 сделать также, очень нужно для биндирования к robovm
спасибо!

**Comment by mobile-ads-github** [comment]
Добрый день! В версии SDK 5.0.0 отказались от использования динамического фреймворка, т. к. он не предоставляет никаких преимуществ перед статическим. В дальнейшем рассмотрим вариант возвращения динамического фреймворка.

**Comment by noname1980** [comment]
добрый день! да, большая просьба к Вас осуществить опять поддержку динамического фреймворка (Dynamic), т.к. даже у вас в инструкции написано, скачать динамический фреймворк можно так pod 'YandexMobileAds/Dynamic', '5.0.0', но ничего не качается (ссылка: https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/ios-ads-component.html). На текущий момент Метрика у вас идёт как динамик и статик.

**Comment by mobile-ads-github** [comment]
Спасибо за замечания, инструкцию поправили.

**Comment by noname1980** [comment]
спасибо, надеюсь всё таки будет динамик версия 5.0.0, а то пока приходится сидеть на версии 4.4.3 ))) (притом что вы её тут недавно обновили вчера). Без динамик совсем никак не могу слинковать, вручную сконвертировать тоже пока не получилось (static -> dynamic)
