### ISSUE TITLE
YMAInterstitialAd при показе выдаёт "Incorrect fullscreen view" (OpenGL) (SDK 4.4.2)

### ISSUE THREAD

**Issue by noname1980** [yandexmobile/yandex-ads-sdk-ios#102]
У меня базовый view контрол GLKViewController (OpenGL приложение), при попытке показать рекламу YMAInterstitialAd через presentFromViewController выдаёт ошибку errorCode:10, error:Error Domain=com.yandex.mobile.YandexMobileAds Code=10 "Incorrect fullscreen view" UserInfo={NSLocalizedDescription=Incorrect fullscreen view}
при этом Баннер работает идеально - всё показывает (и тестовую рекламу и не_тестовую).
попробовал также YMARewardedAd - также показывает всё отлично (и тестовое видео и не_тестовое видео).
при этом вижу что reward работает через ваш внутренний класс YMARotatingFullscreenViewController, наверно поэтому всё показывает хорошо.
при этом и в interstitial  и в reward передаю rootViewController (UIApplication.shared.windows.first!.rootViewController!)
такой же подход при показе рекламы в google_admob (передаю rootViewController) - там interstitial работает.

SDK 5.0.0 попробовать не могу, т.к. нет dynamic фреймворка пока что...
пробовал еще версию 4.3.1 - такая же проблема с interstitial

скачал ваши Examples  тут на сайте, да эти примеры работают нормально - interstitial показывает, но базовое окно не opengl...

**Comment by mobile-ads-github** [comment]
Добрый день! Подскажите, пожалуйста, как вы подключаете нашу библиотеку? Если вы используете не cocoa pods, а напрямую, то нужно не забыть подключить bundle.

**Comment by noname1980** [comment]
да, подключаю напрямую. Всё заработало! Спасибо за подсказку, добавил bundle в ресурсы - теперь всё показывает.
