### ISSUE TITLE
YMAAdView (реклама Баннер) при вызове displayAtBottomInView цепляет к полоске на iPhone 11/12

### ISSUE THREAD

**Issue by noname1980** [yandexmobile/yandex-ads-sdk-ios#103]
Приложение полноэкранное-OpenGL (GLKViewController), вызываю баннерную рекламу YMAAdView, далее при вызове displayAtBottomInView цепляет к полоске на iPhone 11/12, а если запустить на iPhone 8/se 2020 то цепляет именно к низу экрана (т.к. этой полосы там нет, переключателя задач).
Эта полоска в полноэкранном OpenGL приложении пропадает сама.
Пока обошёл этот момент так - вызываю displayAtTopInView (сверху ничего нет, цепляет именно чётко к верху), а дальше через setFrame опускаю вниз вплотную к низу экрана.
Может быть можно сделать для такого 2 отдельных метода опускания вниз...

SDK 4.4.2

**Comment by mobile-ads-github** [comment]
Добрый день! Вы можете не использовать наш метод, а сами выставлять нужное положение для баннера.

**Comment by noname1980** [comment]
окей

**Comment by mobile-ads-github** [comment]
Добрый день! Небольшое дополнение, мы рекомендуем использовать наш метод, так как он отображает рекламу в границах safe area, как этого требует [apple human interface guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/)

**Comment by noname1980** [comment]
добрый день! спасибо за пояснение! я пробовал без вашего метода, только setFrame, но не работало - не видел объявление, через ваш метод displayAtTopInView  - всё показывается чётко, потом только опускаю к нижней границы и всё. Везде всё протестировал - на всех симуляторах и реальных девайсах - всё работает отлично! Спасибо!

п.с. будет у вас время сделаете еще для версии 5.0.0 динамик фреймворк и будет вообще замечательно!
