### ISSUE TITLE
Ошибка загрузки на версиях выше iOS 14

### ISSUE THREAD

**Issue by CroperMR** [yandexmobile/yandex-ads-sdk-ios#107]
При загрузке рекламы выдается ошибка:
`AdFox loading error: Error Domain=com.yandex.mobile.YandexMobileAds Code=3 "Ad request completed successfully, but there are no ads available" UserInfo={NSLocalizedDescription=Ad request completed successfully, but there are no ads available}`

На iOS ниже 14 та же реклама загружается без проблем.
ATTrackingManager запрашивает получение IDFA, юзер дает согласие.

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за сообщение о проблеме.
Пришлите пожалуйста id рекламного блока и id приложения на почту mobile-ads-github@yandex-team.ru для того, чтобы мы могли подробнее разобраться в причинах возникновения проблемы.

**Comment by mobile-ads-github** [comment]
Подбор рекламы на разных девайсах для разных пользователей отличается. Для указанных блоков реклама подбирается в том числе и на iOS версии 14 и выше. 
Для улучшения подбора рекомендуем реализовать шаги, указанные в документации https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/support-ios-14.html, в том числе и поддержку SKAdNetwork.
