### ISSUE TITLE
Под YandexMobileAds/Dynamics не работает с версии 5.0.0

### ISSUE THREAD

**Issue by abdulowork** [yandexmobile/yandex-ads-sdk-ios#109]
# Окружение
* Xcode 13.0
* CocoaPods 11.2

# Шаги для воспроизведения
1. Создать пустой iOS проект
2. Сделать `pod init`
3. Добавить в Podfile: `pod 'YandexMobileAds/Dynamic'`
4. Добавить в какой-нибудь файл `import YandexMobileAds`
5. Сделать `pod install` и собрать проект

## Ожидаемое поведение
Проект собирается

## Реальное поведение
Сборка падает с ошибкой `No such module 'YandexMobileAds'`

**Comment by dmitryfisko** [comment]
Добрый вечер! Мы перестали поддерживать dynamic способ подключения начиная с версии 5.0.0. Необходимо использовать static способ подключения.
https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/ios-ads-component.html

**Comment by mobile-ads-github** [comment]
Добрый вечер! Мы перестали поддерживать dynamic способ подключения начиная с версии 5.0.0. Необходимо использовать static способ подключения.
https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/ios-ads-component.html

**Comment by abdulowork** [comment]
Ок! Тогда возможно стоит его удалить, чтобы при обновлении было понятно, что этот сабспек больше не поддерживается.
