### ISSUE TITLE
Label with NSAttributedStrings

### ISSUE THREAD

**Issue by bimawa** [yandexmobile/yandex-ads-sdk-ios#11]
Здравствуйте, ребят. Подскажите пожалуйста, мы используем нативную интеграцию SDK и судя по всему, `bindContentAdToView:delegate:error:` мапинтся на UILabel,  и перезаписывает свойство `text`. А мы по дизайну используем `attributeString`.  Посоветуйте, пожалуйста, наиболее легальную интеграцию.

**Comment by kanstantsin** [comment]
Здравствуйте.
В данной ситуации можно заменить свойство ```attributedText``` у нужной ```UILabel``` после вызова ```bindContentAdToView:delegate:error:```.
Показ будет засчитан, если при этом не изменяется содержимое свойства ```text``` у соответствующей ```UILabel```. Чтобы убедиться, что показ засчитан, можно включить логирование SDK и дождаться вывода текста "Ad binding successful" в лог.

**Comment by bimawa** [comment]
Да ура! То что нужно и логируется данное сообещние успешно!
