### ISSUE TITLE
Проблема с засчитыванием кликов

### ISSUE THREAD

**Issue by 4tune** [yandexmobile/yandex-ads-sdk-ios#111]
Как альтернативу AdMob добавили баннерную рекламу Yandex. При этом приложение уже использует стороннее SDK которое тоже использует данный модуль (там правда, насколько понимаем только видео реклама). 
После запуска видим что показатели по кликам сильно ниже референса в AdMob и наши попытки скликивать рекламу для тестов тоже не видны в статистике.
Куда можно смотреть? Может ли быть проблема следствием совмещения либ в разных модулях?

**Comment by mobile-ads-github** [comment]
Здравствуйте! Cпасибо за вопрос. Проверьте, пожалуйста, что ваше стороннее SDK использует достаточно новую версию Yandex Mobile Ads SDK. Рекомендуем использовать последнюю версию 5.0.2. Для более детального разбора, пришлите пожалуйста ваш ad unit id на нашу почту mobile-ads-github@yandex-team.ru.
