### ISSUE TITLE
Высокая загрузка процессора при обработке ответов

### ISSUE THREAD

**Issue by pavelhiq** [yandexmobile/yandex-ads-sdk-ios#113]
При попытках преобразования ответа часто (десятки тысяч пользователей) наблюдается высокая загрузка процессора, что отражено в отчетах "High CPU Usage" или "High CPU usage termination" органайзера Xcode. Типичный бэктрейс:

```
-[YMAAdLoaderRequestRunner handleResponse:data:request:error:]
...
  -[YMANativeAdResponseConverter adResponseWithJSONString:request:properties:type:mediationData:error:]
  ...
    -[YMAHTMLEntitiesConverter stringByUnescapingHTMLEntitiesInString:]
      -[NSRegularExpression(NSMatching) matchesInString:options:range]
```

Версия библиотеки пока еще 4.1.2. Наблюдается вне зависимости от версии iOS.

**Comment by mobile-ads-github** [comment]
Добрый день! Данная проблема решена в новых версиях SDK, рекомендуем обновиться до последней версии 5.0.2.
