### ISSUE TITLE
При голой сборке проекта сразу накидывает ряд ошибок 

### ISSUE THREAD

**Issue by Kabudasay** [yandexmobile/yandex-ads-sdk-ios#115]
делаю все по шагам перечисленным в readme

Install [CocoaPods](http://cocoapods.org/) to manage project dependencies, if you haven't done it yet.
Go to Examples/YandexMobileAdsExample
Install dependencies: pod install --repo-update
Open the YandexMobileAdsExample.xcworkspace file with Xcode.
Build and run.
Далее ловлю такую картинку
![image](https://user-images.githubusercontent.com/11681789/170241780-3a7603e5-c0ae-44ea-a6d0-7f1056555979.png)
У меня m1 но как я вижу симуляторы подогнаны под arm64

**Comment by mobile-ads-github** [comment]
Добрый день! Проблема заключается в том, что [IronSource не поддерживает m1](https://github.com/CocoaPods/Specs/blob/master/Specs/7/7/b/IronSourceSDK/7.2.1.2/IronSourceSDK.podspec.json#L27).
