### ISSUE TITLE
Высокая загрузка процессора при обработке ответов (re-opened)

### ISSUE THREAD

**Issue by pavelhiq** [yandexmobile/yandex-ads-sdk-ios#118]
Добрый день! Данная проблема решена в новых версиях SDK, рекомендуем обновиться до последней версии 5.0.2.

_Originally posted by @mobile-ads-github in https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/113#issuecomment-1134288631_

Добрый день! К сожалению, та же проблема сохранилась и после обновления SDK до последней версии :( Уверенно top-1 по количеству фиксируемых high-cpu-usage/termination отчётов.

**Comment by mobile-ads-github** [comment]
Добрый день! Действительно проблема не была до конца. Решение появиться в версии sdk 5.2.1. Релиз планируется на следующей неделе.

**Comment by mobile-ads-github** [comment]
Выпустили релиз 5.2.1 в котором проблема была решена
