### ISSUE TITLE
-adViewDidFailLoading:error: not called!

### ISSUE THREAD

**Issue by staskochkin** [yandexmobile/yandex-ads-sdk-ios#12]
Method from YMAAdViewDelegate protocol adViewDidFailLoading: error: never called. I double check my integration. If banner is successfully loaded i get callback adViewDidLoad:, but if ad server return no content (see it in Charles) nothing happened. 
Also I reproduce it on your demo app (from this repository)

**Comment by kanstantsin** [comment]
Hi!
Sorry, can't reproduce your issue with SDK 2.7.0 in our demo app.
Can you provide your SDK version, block ID, sample code and Charles report to reproduce it? Any of those would we helpful.

**Comment by staskochkin** [comment]
Hello! Thanks for fast reply!
I use SDK 2.7.0. 
Integration code - it's  just your demo with additional logging (to see view controller life time). Also contains my block ID:
https://pastebin.com/dvQza4pN

Log for unsuccessful session:
https://pastebin.com/uJED8Pn6

Charles session:
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/35497/2440054/UVWy43Q0zeSSfsq/yandex_banner.chls

**Comment by kanstantsin** [comment]
Sorry, still can't reproduce the issue, even after pasting your code, running it on iOS 8, 9, 10.3 Simulator, iOS 10.3.2 device, replacing response with one you provided. The ```adViewDidFailLoading:error:``` delegate method is being called with ```YMAAdErrorCodeNoFill``` error code.

Do you experience same issue on other iOS versions, devices or simulators?
Do you experience same issue with other block IDs? 
Is it 100% reproducible on your side? You can check it by making an ad unit with very high CPM floor so, that it's very likely that SDK can't fetch ad for it. You can try to make a couple of ad requests and watch how many times delegate methods are called.

**Comment by staskochkin** [comment]
Ok, I continue to research this issue on my side. I reproduce it on iOS 10 on simulator and device (iPhone 7). This reproduce also with older versions of SDK. 
Maybe it some server (look at https://mobile.yandexadexchange.net) response processing issue?

**Comment by kanstantsin** [comment]
We tried getting real 204 from backend (by using high CPM floor) and replacing server response with Charles. In both cases delegate method was called.
The only idea I have right now is that it's some proxy issue (response doesn't come back to app) or specific app state. But it's quite weird that we're using same SDK and application code for debug, same response text, but get different behavior.
Did you encounter this issue before or did it appear after any update of SDK or ad units?

**Comment by staskochkin** [comment]
I firstly integrate YandexMobileAds. In response that SDK received from ad exchange returned 204 code, but response also contains headers fields 
Content-Encoding: gzip
Content-Length: 20

And it's strange

**Comment by kanstantsin** [comment]
I tried different versions of Charles. Indeed, when using Charles 3 connection hangs forever in case of 204 response. But with Charles 4 everything is fine. It's also fine with no proxy connected.

**Comment by staskochkin** [comment]
Thanks! I update Charles to 4 version and everything works fine!
