### ISSUE TITLE
Плагин для Flutter

### ISSUE THREAD

**Issue by mtrfnvwork** [yandexmobile/yandex-ads-sdk-ios#122]
Добрый день!

С учетом ситуации в мире было бы очень кстати иметь плагин для Flutter. Планируется ли его разработка?

**Comment by mobile-ads-github** [comment]
Здравствуйте, поддержка плагина планируется, но пока не можем сообщить конкретных сроков релиза

**Comment by kovardin** [comment]
@mtrfnvwork я, конечно не знаю, нужно оно тебе или нет. Почти полгода уже прошло, много воды утекло... Сейчас зима и непонятно как оно будет дальше...

Но вот либа под flutter https://pub.dev/packages/flutter_yandex_ads

Надеюсь, она сделает твою жизнь чуточку лучше.

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Был выпущен в релиз плагин для flutter.
Пример использования данного плагина вы можете найти по [ссылке](https://github.com/yandexmobile/yandex-ads-flutter-plugin/issues)
