### ISSUE TITLE
Не работает делегат

### ISSUE THREAD

**Issue by dkarat** [yandexmobile/yandex-ads-sdk-ios#129]
Код:

import Foundation
import YandexMobileAds
import UIKit

class RewardedViewController: NSObject, YMARewardedAdDelegate {
    
    var rewardedAd: YMARewardedAd?
    
    func showAdd(){
        self.rewardedAd = YMARewardedAd(adUnitID: "R-M-DEMO-SAMPLE")
        self.rewardedAd?.delegate = self
        self.rewardedAd?.load()
    }
    
    func rewardedAd(_ rewardedAd: YMARewardedAd, didReward reward: YMAReward) {
        let _ = "Rewarded ad did reward: \(reward.amount) \(reward.type)"
        
    }
    
    func rewardedAdDidFail(toLoad rewardedAd: YMARewardedAd, error: Error) {
        print("Loading failed. Error: %@", error)
       
    }
    
    func rewardedAdDidFail (toPresent rewardedAd: YMARewardedAd, error: Error) {
        print("Loading failed. Error: %@", error)
    }
    
    func rewardedAdDidLoad(_ rewardedAd: YMARewardedAd) {
        print("Rewarded ad loaded")
       
    }
    
    func rewardedAdDidDisappear(_ rewardedAd: YMARewardedAd) {
        print("Rewarded ad did disappear")
        
    }
}

Вызов

let delegate = RewardedViewController()
delegate.showAdd()

Ни один колбэк в делегате не срабатывает. Почему ?

**Comment by mobile-ads-github** [comment]
Добрый день!
Проверьте пожалуйста что сохраняется сильная ссылка на RewardedViewController, а также на YMARewardedAdDelegate.
Также рекомендуем проверять загрузку рекламы при помощи демо блока, например <AdUnitID> R-M-DEMO-rewarded-client-side-rtb.
