### ISSUE TITLE
В чем разница адаптеров

### ISSUE THREAD

**Issue by bimawa** [yandexmobile/yandex-ads-sdk-ios#13]
AdMobYandexMobileAdsAdapters
YandexMobileAdsAdMobAdapters

Что мне использовать для показа нативной рекламы и MoPub?

**Comment by kanstantsin** [comment]
Ни один их этих фреймворков не подходит для MoPub.
Если имеется в виду использование нативной рекламы Yandex Mobile Ads через медиацию MoPub, то это пока что находится в стадии эксперимента. Чтобы принять участие в нем, можно написать по адресу michkovam@yandex-team.ru .

И да, названия вводят в заблуждение, переименуем так, чтобы стало понятнее, для чего нужен каждый из фреймворков.

**Comment by bimawa** [comment]
@kanstantsin Костя, у нас уже есть нативная реклама, работает хорошо. Но Гугл откзывается от adMob в сторону MoPub в связи с этим нужно загрузить рекламу яндекса по той же схеме что у нас была через AdMob. Как я понял.

**Comment by bimawa** [comment]
Т.е. по идее адаптеры YandexMobileAdsMoPubAdapters меня полностью должны удовлетворить ? )

**Comment by kanstantsin** [comment]
Я не совсем понимаю несколько вещей:

>Но Гугл откзывается от adMob в сторону MoPub

AdMob - технология Google, MoPub - технология Twitter.  В чем заключается отказ Google от AdMob в сторону MoPub?

>а у нас еще была и реклама яндекса через медиаторы adMob

Требуется перейти с медиации посредством AdMob на медиацию посредством MoPub? Тогда да, нужно вместо  ```YandexMobileAdsAdMobAdapters``` подключить ```YandexMobileAdsMoPubAdapters``` и пользоваться API MoPub для загрузки и показа рекламы.

>Показ нативной рекламы сейчас работает через pods либу YandexMobileAds

Немного путает то, что ранее говорится про медиацию, а тут говорится про нативную рекламу. Адаптеров для нативной рекламы в данный момент нет ни для одной из медиационных платформ. Возможно, в приложении есть нативная реклама, подключенная напрямую одновременно с HTML рекламой, работающей через медиацию?

**Comment by bimawa** [comment]
>AdMob - технология Google, MoPub - технология Twitter. В чем заключается отказ Google от AdMob в сторону MoPub?

Да мы используем DFP коннектор через который подключаются кучка медиаций в том числе и adMob и MobPub, и как мне сказали рекламщики adMob вроде как прикрывают.

>Требуется перейти с медиации посредством AdMob на медиацию посредством MoPub? Тогда да, нужно вместо YandexMobileAdsAdMobAdapters подключить YandexMobileAdsMoPubAdapters и пользоваться API MoPub для загрузки и показа рекламы.

Ага ок. спасибо.

>Немного путает то, что ранее говорится про медиацию, а тут говорится про нативную рекламу. Адаптеров для нативной рекламы в данный момент нет ни для одной из медиационных платформ. Возможно, в приложении есть нативная реклама, подключенная напрямую одновременно с HTML рекламой, работающей через медиацию?

Да да прости, Костя. Просто были не понятные конфликты и я думал это связано с pods`ами. Но сейчас разобрался, не бери в голову. в общем ок пока вопрос снят. Спасибо большое!
