### ISSUE TITLE
Предупреждение из CoreLocation

### ISSUE THREAD

**Issue by sskurzhanskiy** [yandexmobile/yandex-ads-sdk-ios#130]
Много предупреждений:
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

Xcode 14.1
![IMAGE 2022-11-08 11:13:37](https://user-images.githubusercontent.com/23315307/200510189-558e769f-fa8f-464b-b983-c92bb986de6f.jpg)

**Comment by iDevPro** [comment]
The same problem

**Comment by mobile-ads-github** [comment]
Добрый день. Cпасибо, что сообщили о проблеме. Будем разбираться.

**Comment by mobile-ads-github** [comment]
Добрый день! В релизе 5.4.0 данная ошибка должна пропасть.

**Comment by iDevPro** [comment]
The application won't install in simulator with issue "CFBundleShortVersionString not found" after update to 5.4.0
