### ISSUE TITLE
Error building with Xcode 13.2.1

### ISSUE THREAD

**Issue by dovanvu1792** [yandexmobile/yandex-ads-sdk-ios#133]
Xcode 13.2.1(13C100), Mac Big Sur 11.6.5 (20G527) (Intel)
Error when build example project 
-> DivKit_LayoutKit (13.0.0)
<img width="875" alt="Screen Shot 2022-11-22 at 18 07 10" src="https://user-images.githubusercontent.com/8123256/203299222-e11929f9-a927-4eae-9428-23c08684dfa1.png">

**Comment by mobile-ads-github** [comment]
Good day! You should use Swift 5.7 version. We will force it in podspec in future releases to avoid such errors. Thank you.

**Comment by dovanvu1792** [comment]
Ohhhh, How to convert this line to Swift 5?

**Comment by mobile-ads-github** [comment]
We'd recommend to use swift 5.7 in youк project rather than converting source code of 3d party library. In the next patch of our SDK this hack wouldn't work.
