### ISSUE TITLE
Release 5.3.1 YandexMobileAds 5.3.0

### ISSUE THREAD

**Issue by Algashev** [yandexmobile/yandex-ads-sdk-ios#136]
Указан `Release 5.3.1`, а по факту при установке pod'ов в проекте `YandexMobileAdsExample` для `YandexMobileAds` доступна только версия **5.3.0**.

**Comment by mobile-ads-github** [comment]
Добрый день! Релиз 5.3.1 доступен и в репозитории cocoapods есть соответствующая [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/a/c/5/YandexMobileAds/5.3.1/YandexMobileAds.podspec.json).
Для получения новой версии сдк нужно:
- или сделать `pod update YandexMobileAds`
- или прописать явную зависимость pod 'YandexMobileAds', '5.3.0'

**Comment by Algashev** [comment]
День добрый! Я использую ваш проект `YandexMobileAdsExample`. И **Podfile**, который в нем прописан:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '12.0'

target 'YandexMobileAdsExample' do
  pod 'YandexMobileAdsAdMobAdapters'
  pod 'YandexMobileAdsIronSourceAdapters'
  pod 'YandexMobileAdsMediation'
end
```

**Comment by mobile-ads-github** [comment]
обновление YandexMobileAdsMediation еще не успело прорасти в репозиторий cocoapods, там выставлена явная зависимость на sdk версии 5.3.0. в ближайшее время прорастет обновление этой подспеки и вы сможете сделать pod update

**Comment by mobile-ads-github** [comment]
Сейчас все должно обновиться корректно.
