### ISSUE TITLE
Как установить только определённый адаптер?

### ISSUE THREAD

**Issue by NikKovIos** [yandexmobile/yandex-ads-sdk-ios#139]
https://yandex.ru/dev/mobile-ads/doc/ios/mob-mediation/ios-ads-component.html

Исходя из этой статьи я добавил `pod 'AdMobYandexMobileAdsAdapters', '9.13.0.0'` и у меня установилось 

```
Installing AppLovinSDK (11.5.5)
Installing AppLovinYandexMobileAdsAdapters (11.5.5.0)
Installing IronSourceSDK (7.2.5.1)
Installing IronSourceYandexMobileAdsAdapters (7.2.5.0)
Installing MyTargetYandexMobileAdsAdapters (5.17.0.0)
Installing UnityAds (4.4.1)
Installing UnityAdsYandexMobileAdsAdapters (4.4.1.0)
Installing YandexMobileAdsMediation (5.3.1)
Installing myTargetSDK (5.17.1)
Installing myTrackerSDK (3.0.7)
```

В статье написано что можно установить только что-то одно, например мне нужен только AdMob от гугла.
<img width="933" alt="Снимок экрана 2022-12-17 в 16 08 27" src="https://user-images.githubusercontent.com/16647690/208243552-5f759c86-5742-4d2e-ac2c-05341cac7e79.png">

Но не пойму как это сделать?

**Comment by mobile-ads-github** [comment]
Добрый день! Не могли бы вы предоставить Podfile? Все медиационные адаптеры устанавливаются только в случае, если прописано `pod 'YandexMobileAdsMediation', '5.3.1'`.

**Comment by NikKovIos** [comment]
pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'YandexMobileAds', '5.3.1'
  pod 'YandexMobileAdsInstream', '0.13.0'
  pod 'AdMobYandexMobileAdsAdapters', '9.13.0.0'
  pod 'YandexMobileAdsMediation', '5.3.1'

**Comment by mobile-ads-github** [comment]
Удалите последний pod. Он в себе объединяет все медиационные адаптеры.
