### ISSUE TITLE
App crashes after calling presentInterstitial

### ISSUE THREAD

**Issue by AleyRobotics** [yandexmobile/yandex-ads-sdk-ios#14]
Swift 3.0
YMAVersion 2.7.1.0
iPhone 5, 5s, 6, 6s
iOS 10.3.3

calling

`if fullScreenBannerYandex?.loaded == true { 
   fullScreenBannerYandex?.presentInterstitial(from: rootVC)
}`

Stable crash

**back trace**
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x9160c1b0)
    frame #0: 0x1a40c694 libobjc.A.dylib`objc_retain + 4
    frame #1: 0x2065b3c8 UIKit`__39-[UIWindow _noteOverlayInsetsDidChange]_block_invoke_2 + 92
    frame #2: 0x20cc8f92 UIKit`__51-[FBSScene(UIApp) updateUIClientSettingsWithBlock:]_block_invoke + 214
    frame #3: 0x1ca204fa FrontBoardServices`__46-[FBSSceneImpl updateClientSettingsWithBlock:]_block_invoke + 10
    frame #4: 0x1ca20546 FrontBoardServices`-[FBSSceneImpl updateClientSettingsWithTransitionBlock:] + 54
    frame #5: 0x1ca204ec FrontBoardServices`-[FBSSceneImpl updateClientSettingsWithBlock:] + 78
    frame #6: 0x20cc8e90 UIKit`-[FBSScene(UIApp) updateUIClientSettingsWithBlock:] + 108
    frame #7: 0x2065b356 UIKit`__39-[UIWindow _noteOverlayInsetsDidChange]_block_invoke + 144
    frame #8: 0x2061c982 UIKit`_runAfterCACommitDeferredBlocks + 276
    frame #9: 0x2060fc92 UIKit`_cleanUpAfterCAFlushAndRunDeferredBlocks + 524
    frame #10: 0x203918bc UIKit`_afterCACommitHandler + 112
    frame #11: 0x1b127802 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
    frame #12: 0x1b125a54 CoreFoundation`__CFRunLoopDoObservers + 282
    frame #13: 0x1b126016 CoreFoundation`__CFRunLoopRun + 1358
    frame #14: 0x1b0791ae CoreFoundation`CFRunLoopRunSpecific + 470
    frame #15: 0x1b078fd0 CoreFoundation`CFRunLoopRunInMode + 104
    frame #16: 0x1c823b40 GraphicsServices`GSEventRunModal + 80
    frame #17: 0x20401a52 UIKit`UIApplicationMain + 150
  * frame #18: 0x002313f4 Sport-swift`main at AppDelegate.swift:17
    frame #19: 0x1a8664ea libdyld.dylib`start + 2

**Comment by kanstantsin** [comment]
Thank you for report, we will try to look into this problem as soon as possible.
Meanwhile, could you attach a small sample project for us to reproduce the issue?

**Comment by kanstantsin** [comment]
Unfortunately, we couldn't reproduce the issue. It looks like kind of very specific case. So, we're putting this issue on hold until we have crashing sample project or at least detailed steps to reproduce the crash.
