### ISSUE TITLE
Невозможно выполнить сборку в XCode 14.2 используя SwiftPackageManager

### ISSUE THREAD

**Issue by Reactor13** [yandexmobile/yandex-ads-sdk-ios#141]
Приветствую,

Не получается корректно выполнить установку пакета через SwiftPackageManager и выполнить сборку в XCode 14.2

1. Пробовал на чистом проекте и на рабочем. Оба SwiftUI. Но дело не доходит до отображения рекламы, тк сборка проекта не выполняется.
2. При использовании SwiftPackageManger содержимое пакета не соответствует содержимому, которое представлено в инструкции. Кроме того в нем нет YandexMobileAdsBundle.bundle (его можно найти в artifacts, но это не решает проблему).

YandexMobileAdsBundle.bundle теперь находится здесь:
<img width="935" alt="Снимок экрана 2023-01-17 в 13 34 50" src="https://user-images.githubusercontent.com/7979883/212900581-ed0e09bd-297c-4e03-8209-3750713ae64b.png">

Вот так отображается содержимое пакетов в XCode 14.2:
<img width="261" alt="Снимок экрана 2023-01-17 в 13 36 36" src="https://user-images.githubusercontent.com/7979883/212900844-3304a0b2-cce2-4497-941f-de2fdc0713d3.png">

А вот так в вашей инструкции:
<img width="201" alt="Снимок экрана 2023-01-17 в 13 37 41" src="https://user-images.githubusercontent.com/7979883/212900950-062c793d-404a-4486-ad86-20ac5f1af412.png">

3. Итак я все же нашел и подключил в сбоку YandexMobileAdsBundle.bundle. Но сборка не выполняется со следующими ошибками. Так и на чистом проекте и на рабочем. 

Что я делаю не так? В чем проблема? Те видно, что не хватает YXMobileAdsBase, YXMobileAdsPlatformDescription, YXMobileAdsDependenciesUmbrella. А как их установить?

```
Could not find or use auto-linked framework 'YXMobileAdsBase'
Could not find or use auto-linked framework 'YXMobileAdsPlatformDescription'
Could not find or use auto-linked framework 'YXMobileAdsDependenciesUmbrella'
Undefined symbol: _$s10CommonCore15ImageContainingMp
Undefined symbol: _$s10CommonCore21VisibleBoundsTrackingMp
Undefined symbol: _$s10CommonCore25VisibleBoundsTrackingLeafMp
Undefined symbol: _$s10CommonCore25VisibleBoundsTrackingLeafPAAE02oncD7Changed4from2toySo6CGRectV_AHtF
Undefined symbol: _$s10Networking18ImageHolderFactoryV05localB8Provider25imageProcessingQueueLabel16requestPerformerAcA05LocalB9Providing_pSg_SSAA20URLRequestPerforming_ptcfC
Undefined symbol: _$s10Networking19LocalImageProvidingMp
``` 
и т.д. (всего 100 ошибок)

4.

Вот так еще сборка выполняется:
```
import SwiftUI
import YandexMobileAds

@main
struct TestApp: App {
    
    init() {
        var rewardedAd: YMARewardedAd!
        //rewardedAd = YMARewardedAd(adUnitID: "demo-rewarded-yandex")
   }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

А так уже нет:
```
import SwiftUI
import YandexMobileAds

@main
struct TestApp: App {
    
    init() {
        var rewardedAd: YMARewardedAd!
        rewardedAd = YMARewardedAd(adUnitID: "demo-rewarded-yandex")
   }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Спасибо за информацию, поправили ошибку, рекомендуем удалить package из проекта и добавить повторно, для удаления кешей.
Актуальная версия 5.4.0.
