### ISSUE TITLE
Generate Info.plist file Build Settings cause unexpected behaviour

### ISSUE THREAD

**Issue by kerimdeveci** [yandexmobile/yandex-ads-sdk-ios#142]
We are using this SDK with Unity plugin through Applovin, AppLovinMediationYandexAdapter adds YandexMobileAds library to the project as a dependency on the Xcode side, this library sets the build settings named `GENERATE_INFOPLIST_FILE` to `YES` in the cocoapod settings, this causes the Info.plist already created in the project to be override with the existing Xcode build settings. Since the version strings are only transferred to the Info.plist file during Unity build in the project. it behaves as if no version has been set, For this reason, GENERATE_INFOPLIST_FILE settings should be removed

**Comment by uchar** [comment]
When are you going to fix this?

**Comment by mobile-ads-github** [comment]
Hi! Can you please specify the version of YandexMobileAds and AppLovinMediationYandexAdapter used in the project?

**Comment by uchar** [comment]
@mobile-ads-github Hi, 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/5172296/219590521-b7caeeb2-1cb6-4d64-8664-c77190c4dd42.png">

**Comment by kerimdeveci** [comment]
@uchar , workaround for unity using post process script
`project.SetBuildProperty(mainTargetGuid, "GENERATE_INFOPLIST_FILE", "NO");`

**Comment by pingvigames** [comment]
Have you tested version 5.8.3 applovin unity sdk (with your fix) with Yandex adapter? Upgrading to the new version did not help us. We still have "The Info.plist in the package must contain the CFBundleVersion key. Unable to validate your application."
Try to build with sdk 5.8.3 + yandex adapter + fb sdk

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25152305. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp10.07.2023, 18:19, "mobile-ads-github" ***@***.***>:
Closed #142 as completed.
