### ISSUE TITLE
Невозможно выполнить сборку, используя Cocoapods

### ISSUE THREAD

**Issue by mobileapps23** [yandexmobile/yandex-ads-sdk-ios#146]
Добрый день!
1. Использую способ установки, описанный в документации (Xcode 14.1), прописываю в Podfile

```
pod 'YandexMobileAds', '5.4.0'
pod 'YandexMobileAdsInstream', '0.13.0'
```
Ошибка в терминале:
```
[!] CocoaPods could not find compatible versions for pod "YandexMobileAds":
  In Podfile:
    YandexMobileAds (= 5.4.0)

    YandexMobileAdsInstream was resolved to 0.13.0, which depends on
      YandexMobileAds (~> 5.3.0)

Specs satisfying the `YandexMobileAds (= 5.4.0), YandexMobileAds (~> 5.3.0)` dependency were found, but they required a higher minimum deployment target.
```
minimum deployment target установлен 13.0

2. Если прописывать версии
```
pod 'YandexMobileAds', '~> 5.3.0'
  pod 'YandexMobileAdsInstream', '0.13.0'
```
то при сборке проекта получаю ошибку

<img width="615" alt="image" src="https://user-images.githubusercontent.com/40164951/217811688-996e18a1-f569-49da-9ba1-1b34d156b7c6.png">
[Здесь](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/141) было отвечено, что эта ошибка была устранена в версии 5.4.0, но я не могу ее установить из-за конфликта версий, см.п.1

Как корректно выполнить сборку используя Cocoapods?

**Comment by mobile-ads-github** [comment]
Добрый день! Попробуйте выполнить сборку с более новой версией Instream.
```
pod 'YandexMobileAds', '5.4.0'
pod 'YandexMobileAdsInstream', '0.14.0'
```

**Comment by mobileapps23** [comment]
спасибо, pod install прошла без ошибок, но при сборке проекта ошибки -

**Comment by mobile-ads-github** [comment]
К сожалению не удалось воспроизвести эту проблему на чистом проекте 
пришлите пожалуйста ваш podfile и xccongfig

прислать можно или в ишью или на нашу почту mobile-ads-github@yandex-team.ru

**Comment by mobile-ads-github** [comment]
У вас в подфайле прописано для всех таргетов Pods
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

Это при сборке приложения меняет символы для нашей обязательной зависимости DivKit из-за чего мы не можем с ней слинковаться
Вам нужно убрать выставления BUILD_LIBRARY_FOR_DISTRIBUTION в YES и тогда проблем не будет. По идее этот флаг имеет смысл выставлять в YES только если надо собрать SDK в xcframework для распространения, при сборке приложения он не нужен.
Либо не проставляйте флаг только для этого списка зависимостей

DivKit
DivKit_Base
DivKit_BaseTiny
DivKit_BaseUI
DivKit_CommonCore
DivKit_LayoutKit
DivKit_LayoutKitInterface
DivKit_Networking
DivKit_Serialization
DivKit_TemplatesSupport

**Comment by mobileapps23** [comment]
спасибо за оперативную помощь!
