### ISSUE TITLE
В событии didTrackImpressionWith приходит nil

### ISSUE THREAD

**Issue by Harvester-76** [yandexmobile/yandex-ads-sdk-ios#148]
В обработчике YMANativeAdDelegate nativeAd(_ ad: YMANativeAd, didTrackImpressionWith impressionData: YMAImpressionData?) приходит  impressionData, равное nil.

Помогите, пожалуйста, разобраться, в каких случаях такое может происходить и что нужно сделать, чтобы данные приходили?

<img width="859" alt="Снимок экрана 2023-02-21 в 14 50 37" src="https://user-images.githubusercontent.com/80912769/220337760-495d88c4-b966-49a6-880d-78d1ea63eb58.png">

**Comment by mobile-ads-github** [comment]
Здравствуйте, на данный момент фича с приходом этих параметров включается только по договорённости с менеджером
