### ISSUE TITLE
Не работают параметры размеров при запросе рекламы для YMANativeBannerView

### ISSUE THREAD

**Issue by VladimirAvstriychenko** [yandexmobile/yandex-ads-sdk-ios#150]
Добрый день! Запрашиваю рекламу с вот такими параметрами:

private var adView: YMANativeBannerView?
var adLoader: YMANativeAdLoader!
...
let requestConfiguration = YMAMutableNativeAdRequestConfiguration(adUnitID: "R-M-DEMO-native-c")     
requestConfiguration.parameters = [ "preferable-height": "50", "preferable-width": "390" ]
requestConfiguration.shouldLoadImagesAutomatically = true
adLoader.loadAd(with: requestConfiguration)
        
Хочу получить ее в шаблонный YMANativeBannerView, но приходит всегда контент другого, произвольного размера.

<img width="376" alt="Снимок экрана 2023-03-09 в 15 42 31" src="https://user-images.githubusercontent.com/44810613/224029661-71a8899c-faab-4615-a456-cec198f385f8.png">
<img width="476" alt="Снимок экрана 2023-03-09 в 15 43 58" src="https://user-images.githubusercontent.com/44810613/224029668-bd97bc10-b878-40ff-b463-5e7c30caf4b7.png">
<img width="377" alt="Снимок экрана 2023-03-09 в 15 50 19" src="https://user-images.githubusercontent.com/44810613/224029672-e006769b-b71c-43df-b41b-ba9312cb4870.png">

Вопрос - не работают параметры, или я как-то неправильно их передаю для YMANativeAdLoader ?

**Comment by VladimirAvstriychenko** [comment]
Версия через SPM - YandexMobileAdsPackage 5.4.0

**Comment by VladimirAvstriychenko** [comment]
@mobile-ads-github пожалуйста подскажите, в чем может быть проблема, 2 недели ждем(

**Comment by mobile-ads-github** [comment]
Добрый день, извиняемся за ожидание, эти параметры используются только при подборе определенных рекламных продуктов, например медийной рекламы, в вашем случае подобрался директ, и эти параметры никак не участвуют в выборе размера картинки.

**Comment by mobile-ads-github** [comment]
Извините за долгий ответ, возможно уже не актуально, но всё же отвечу.
Параметры которые вы использовали применими только для медийной рекламы, для всех остальных они ничего не делают. В нативной рекламе вы можете сами ограничить размеры объявления навесив констрейты на рекламное вью, но для этого нужно делать полность свою вёрстку, а не использовать нативный шаблон.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25260605. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 11:24, "mobile-ads-github" ***@***.***>:
Closed #150 as completed.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25260607. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 11:24, "mobile-ads-github" ***@***.***>:
Извините за долгий ответ, возможно уже не актуально, но всё же отвечу.
Параметры которые вы использовали применими только для медийной рекламы, для всех остальных они ничего не делают. В нативной рекламе вы можете сами ограничить размеры объявления навесив констрейты на рекламное вью, но для этого нужно делать полность свою вёрстку, а не использовать нативный шаблон.
