### ISSUE TITLE
xcode 13

### ISSUE THREAD

**Issue by canitakeyourecode** [yandexmobile/yandex-ads-sdk-ios#151]
Failed to build module 'YandexMobileAdsInstream'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)'). Please select a toolchain which matches the SDK.

**Comment by canitakeyourecode** [comment]
Но на 14м собирается с версией pod 'YandexMobileAdsInstream', '~> 0.11.0'

**Comment by canitakeyourecode** [comment]
но ваша  0.13.0 не пашет в принципе кроме стандартных сборок !

**Comment by canitakeyourecode** [comment]
ответ то будет какой нибудь ? или вопрос ?

**Comment by mobile-ads-github** [comment]
> но ваша 0.13.0 не пашет в принципе кроме стандартных сборок !

Добрый день, что вы имеете в виду под "кроме стандартных сборок"

Использование XCode 14 должно решать вашу проблему

**Comment by canitakeyourecode** [comment]
Смотрите собираю фреймворк в xCode 14 c крайней версией приложения, замечаю что добавлены divKit 
начинаю собирать и ловлю ряд ошибок

Undefined symbols for architecture arm64:
  "_$s18LayoutKitInterface13UIElementPathV23__derived_struct_equalsySbAC_ACtFZ", referenced from:
      _$ss22__RawDictionaryStorageC4find_9hashValues10_HashTableV6BucketV6bucket_Sb5foundtx_SitSHRzlF18LayoutKitInterface13UIElementPathV_Tgq5 in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6BaseUI14fontSpecifiersAA04FontD0Cvau", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6DivKit0A9FlagsInfoV7defaultACvau", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s8BaseTiny9RGBAColorV5clearACvau", referenced from:
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makeG04data7context9LayoutKit0G0_p0eM00eF4DataV_AI0eG15ModelingContextVtFTf4xnn_n in YandexMobileAds(AdDivCustomBlockFactory.o)
  "_$s9LayoutKit0A5TraitO21__derived_enum_equalsySbAC_ACtFZ", referenced from:
      _$s15YandexMobileAds21AdDivMediaCustomBlockC6equalsySb9LayoutKit0H0_pF in YandexMobileAds(AdDivMediaCustomBlock.o)
      _$s15YandexMobileAds21AdDivMediaCustomBlockC2eeoiySbAC_ACtFZTf4nnd_n in YandexMobileAds(AdDivMediaCustomBlock.o)
      _$s15YandexMobileAds27AdDivMediaCustomBlockHeightOSQAASQ2eeoiySbx_xtFZTW in YandexMobileAds(AdDivMediaCustomBlockHeight.o)
  "_$s9LayoutKit0A5TraitO6WeightV7defaultAEvau", referenced from:
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makede5MediafG15WithAspectRatio33_CEE3487786A6685D64AEB3610D3675BALL02adE10Properties4datas6ResultOyAA0dejfG0CAA0dE8KitErrorOGAA0deU0V_SDySSypGtF in YandexMobileAds(AdDivCustomBlockFactory.o)
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makeG04data7context9LayoutKit0G0_p0eM00eF4DataV_AI0eG15ModelingContextVtFTf4xnn_n in YandexMobileAds(AdDivCustomBlockFactory.o)
      _$s15YandexMobileAds21AdDivMediaCustomBlockC9LayoutKit0H0AadEP027weightOfVerticallyResizableH0AD0I5TraitO6WeightVvgTW in YandexMobileAds(AdDivMediaCustomBlock.o)
  "_$s9LayoutKit13UIActionEventC8uiAction0aB9Interface04UsergF0VvpWvd", referenced from:
      _$s15YandexMobileAds14DivViewWrapperC7perform13uiActionEvent4fromy9LayoutKit08UIActionJ0C_yXltFTf4ndn_n in YandexMobileAds(DivViewWrapper.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

**Comment by canitakeyourecode** [comment]
https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

> > но ваша 0.13.0 не пашет в принципе кроме стандартных сборок !
> 
> Добрый день, что вы имеете в виду под "кроме стандартных сборок"
> 
> Использование XCode 14 должно решать вашу проблему

Прошу прощения не стандартных а более ранних версий например на этой версии все собирается
pod 'YandexMobileAdsInstream', '~> 0.11.0'

**Comment by canitakeyourecode** [comment]
sLocation/Library/Frameworks/NskAdsSDK.framework/NskAdsSDK
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsBase'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsPlatformDescription'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsNetworking'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsSDKConfiguration'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsDependenciesUmbrella'
Undefined symbols for architecture arm64:
  "_$s18LayoutKitInterface13UIElementPathV23__derived_struct_equalsySbAC_ACtFZ", referenced from:
      _$ss22__RawDictionaryStorageC4find_9hashValues10_HashTableV6BucketV6bucket_Sb5foundtx_SitSHRzlF18LayoutKitInterface13UIElementPathV_Tgq5 in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6BaseUI14fontSpecifiersAA04FontD0Cvau", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6DivKit0A9FlagsInfoV7defaultACvau", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s8BaseTiny9RGBAColorV5clearACvau", referenced from:
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makeG04data7context9LayoutKit0G0_p0eM00eF4DataV_AI0eG15ModelingContextVtFTf4xnn_n in YandexMobileAds(AdDivCustomBlockFactory.o)
  "_$s9LayoutKit0A5TraitO21__derived_enum_equalsySbAC_ACtFZ", referenced from:
      _$s15YandexMobileAds21AdDivMediaCustomBlockC6equalsySb9LayoutKit0H0_pF in YandexMobileAds(AdDivMediaCustomBlock.o)
      _$s15YandexMobileAds21AdDivMediaCustomBlockC2eeoiySbAC_ACtFZTf4nnd_n in YandexMobileAds(AdDivMediaCustomBlock.o)
      _$s15YandexMobileAds27AdDivMediaCustomBlockHeightOSQAASQ2eeoiySbx_xtFZTW in YandexMobileAds(AdDivMediaCustomBlockHeight.o)
  "_$s9LayoutKit0A5TraitO6WeightV7defaultAEvau", referenced from:
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makede5MediafG15WithAspectRatio33_CEE3487786A6685D64AEB3610D3675BALL02adE10Properties4datas6ResultOyAA0dejfG0CAA0dE8KitErrorOGAA0deU0V_SDySSypGtF in YandexMobileAds(AdDivCustomBlockFactory.o)
      _$s15YandexMobileAds23AdDivCustomBlockFactoryC04makeG04data7context9LayoutKit0G0_p0eM00eF4DataV_AI0eG15ModelingContextVtFTf4xnn_n in YandexMobileAds(AdDivCustomBlockFactory.o)
      _$s15YandexMobileAds21AdDivMediaCustomBlockC9LayoutKit0H0AadEP027weightOfVerticallyResizableH0AD0I5TraitO6WeightVvgTW in YandexMobileAds(AdDivMediaCustomBlock.o)
  "_$s9LayoutKit13UIActionEventC8uiAction0aB9Interface04UsergF0VvpWvd", referenced from:
      _$s15YandexMobileAds14DivViewWrapperC7perform13uiActionEvent4fromy9LayoutKit08UIActionJ0C_yXltFTf4ndn_n in YandexMobileAds(DivViewWrapper.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


На последней версии библиотеки пытаюсь собрать свой framework с вашим подом

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!
