### ISSUE TITLE
YandexMobileAds/Static 5.5.0 full version in zip file

### ISSUE THREAD

**Issue by noname1980** [yandexmobile/yandex-ads-sdk-ios#152]
Добрый день!

качаю свежую zip версию библиотеки 5.5.0 по пути отсюда
https://github.com/yandexmobile/yandex-ads-sdk-ios/tree/master/changelog/mobileads/CHANGELOG.md

пытаюсь подключить статик фреймворк и получаю такие ошибки линковки
error: Could not find or use auto-linked framework 'YXMobileAdsBase'
error: Could not find or use auto-linked framework 'YXMobileAdsPlatformDescription'
error: Could not find or use auto-linked framework 'YXMobileAdsNetworking'
error: Could not find or use auto-linked framework 'YXMobileAdsSDKConfiguration'
error: Could not find or use auto-linked framework 'YXMobileAdsDependenciesUmbrella'

смотрю на версии ваши и размер...
164M  YandexMobileAds-5.0.0-ios.zip
208M  YandexMobileAds-5.1.0-ios.zip
222M  YandexMobileAds-5.2.0-ios.zip
222M  YandexMobileAds-5.2.1-ios.zip
100M  YandexMobileAds-5.3.0-ios.zip
 26M  YandexMobileAds-5.3.1-ios.zip
9.8M  YandexMobileAds-5.4.0-ios.zip
 10M  YandexMobileAds-5.5.0-ios.zip

в итоге подключаю без ошибок линковки из последних только версию 5.2.1

есть возможность выкладывать полную версию (как было в 5.2.1) YandexMobileAds?

**Comment by mobile-ads-github** [comment]
Спасибо за репорт, мы проверим и вернемся

**Comment by mobile-ads-github** [comment]
Насколько мы поняли, Вы не используете cocoapods, а пытаетесь интегрировать вручную, и видимо не затянули все нужные зависимости.
Вообще мы такой способ не рекомендуем и сейчас официально не поддерживаем. Единственное что можем порекомендовать - использовать cocoapods.

**Comment by noname1980** [comment]
В данной линковке я не использую cocoapods (потому что не родное приложение для xcode), мне нужна целая библиотека чтоб всё внутри было, у вас же было это всё до версии 5.2.1 включительно.
В cocoapods тоже подтягивается очень много зависимостей, но переносить их вообще затратно и смысла мало, из всех зависимостей используется же только доступ к методам показа рекламы YandexMobileAds.
В версии 5.2.1 вы же выкладывали полную библиотеку, а сейчас почему не можете?

**Comment by mobile-ads-github** [comment]
С версии 5.3.0 у SDK появилась внешняя зависимость.
https://github.com/CocoaPods/Specs/blob/master/Specs/a/c/5/YandexMobileAds/5.5.0/YandexMobileAds.podspec.json#L22
Чтобы SDK смогла слинковаться эту библиотеку вместе с её зависимостями тоже нужно добавить в проект.

Планов по вкомпиливанию внешних библиотек в наш фреймворк нет.

**Comment by noname1980** [comment]
а чего DivKit не сделан как xcframework, а набором swift файлов? 
если был бы +1 фреймворк дивкит - проблем бы не было...  а так еще куча зависимостей самого дивкита (загружал версию 5.5 через cocoapods)

p.s. тогда и выкладывать zip архивы смысла не имеет, без зависимостей... либо вкомпилить всё в одно, мало ли кому пригодилось бы) не для всего же есть плагины, как в юнити

**Comment by iDevPro** [comment]
<img width="404" alt="Снимок экрана 2023-06-13 в 10 34 21" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/1888230/3ee7ca4c-4f0f-46ee-910f-219c9071e485">
Адища

**Comment by noname1980** [comment]
>  Адища )))
> Вот и зачем столько зависимостей ?) если надо показать только рекламу ?))))

и это кстати еще не полный список))) ладно там если через cocoapods подтягиваешь все эти зависимости, то как бы всё равно - делается же автоматом... 
а если через прямое подключение надо, через архив zip - вот тогда наступает проблема) хотя бы какую-нибудь версию Lite что ли сделали... 
ну или zip архив полный, пусть даже весил бы 600-900мегов, не страшно, лишь бы подключать всё это одной ссылкой....
про дивкиты я читал на хабре, они замутили свой аналог html/js.... 
а нам реально показать всего лишь рекламку то надо)))

**Comment by mobile-ads-github** [comment]
> <img alt="Снимок экрана 2023-06-13 в 10 34 21" width="404" src="https://user-images.githubusercontent.com/1888230/245392257-3ee7ca4c-4f0f-46ee-910f-219c9071e485.png"> Адища )))
> Вот и зачем столько зависимостей ?) если надо показать только рекламу ?))))

DivKit используется практически во всех рекламных форматах. Это позволяет нам менять дизайн без перевыпуска SDK. Таким образом, большинство UI обновлений у вас оказываются сразу после выкатки.

**Comment by noname1980** [comment]
> 
> DivKit используется практически во всех рекламных форматах. Это позволяет нам менять дизайн без перевыпуска SDK. 
> Таким образом, большинство UI обновлений у вас оказываются сразу после выкатки.

так это ваша "внутренняя кухня"...  для нас это "чёрный ящик"
сделали бы для конечного пользователя вариант с zip архивом, где всё уже есть... (как раньше)
очень удобно было бы для многих

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!
