### ISSUE TITLE
Существует ли версия библиотеки без DivKit ?

### ISSUE THREAD

**Issue by iDevPro** [yandexmobile/yandex-ads-sdk-ios#155]
Добрый день, используем интеграцию рекламы от Яндекса,
однако при обновлении библиотеки скачивается так-же DivKit, ладно бы просто скачивался, так еще и ошибки в консоли получаем 
<img width="263" alt="Снимок экрана 2023-05-24 в 20 14 34" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/1888230/0c0deaf1-a442-45d1-a460-201aa8941e22">

Method '+telephonyInfo' in category from ~/Library/Developer/Xcode/DerivedData/RBCReader-dudhxgmtxbszlwfrduaoxecylonp/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/YandexMobileAds/YandexMobileAds.framework/YandexMobileAds(YXPlatformCurrentState+Telephony.o) conflicts with same method from another category

5.2.1 (без DivKit)
5.4.0 (c DivKit)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение. К сожалению без DivKit теперь нельзя. Он позволяет обновлять дизайн рекламных объявлений с нашей стороны без обновления SDK и перевыпуска Вашего приложения. Это дает возможность  быстрее внедрять обновления дизайна и глобально улучшать как пользовательские метрики так и доход приложений.
Что касается warnings - обновите версию SDK до >=5.6.0, должно помочь.
