### ISSUE TITLE
Крэши на клиентах с SDK 5.4.0 / Нет обратной совместимости

### ISSUE THREAD

**Issue by Reactor13** [yandexmobile/yandex-ads-sdk-ios#157]
С 01 июня наблюдается крэши на клиентах с SDK 5.4.0 при запросе рекламы в блоках с вознаграждением.
Например, в нашем случае 01 июня приложение упало около 11К раз. Почти каждый раз при запросе объявления. В некоторых случаях объявление загружается (в 1 из 10 случаев).

Служба поддержки отвечает шаблонно - актуальная версия SDK 5.7.0. Но вы же понимаете, что должна быть обратная совместимость. В крайнем случае устаревшая библиотека должна просто переставать показывать объявления, а не уводить приложения в крэши. Хорошо, допустим мы обновились до 5.7.0, прошли проверку в Эпле, забили на пользователей которые не обновляют приложение. А дальше? Вы выпускаете 5.8.0, а 5.7.0 не получив обратную совместимость также будет крэшить наши приложения?

Во вложении график роста числа крешей. 3го июня отключили площадку, поэтому крэшней нет.

![крэши](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/7979883/25faa1eb-fb9e-4c65-a863-4f94427a6c87)

Заголовок ошибки:
```
Fatal Exception: NSInvalidArgumentException
-[YMARewardedManager manager:notEnoughSpaceToDisplay:error:]: unrecognized selector sent to instance 0x2813e5930
```

Стэктрейсы высылал в службу поддержки. Могу выслать еще раз, но не в публичный доступ. 

**Я не знаю, наверное, это проблема не в SDK. Скорее на сервере появился какой-то новый формат объявлений, который старые SDK не могут отобразить. Но невозможно пробиться через шаблоны службы поддержки. Пожалуйста, давайте решим эту проблему с обратной совместимостью!**

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо за репорт, смотрим.

**Comment by mobile-ads-github** [comment]
Нашли проблему, планируем выкатить исправление на бэкэнде в течении 2 часов.
Извините за доставленную проблему, спасибо большое за репорт.

**Comment by Reactor13** [comment]
спасибо

**Comment by mobile-ads-github** [comment]
Выпустили исправление на своей стороне, крэшей больше не должно быть.
Проверьте пожалуйста в вашем приложении отсутсвие крэшей при загрузке и показе рекламы.

**Comment by Reactor13** [comment]
> Выпустили исправление на своей стороне, крэшей больше не должно быть. Проверьте пожалуйста в вашем приложении отсутсвие крэшей при загрузке и показе рекламы.

Спасибо за инфо.
Проверим сегодня в ночное время, тк площадка включается и отключается около часа, и чтобы если проблема будет, то пострадало меньше пользователей.

**Comment by Reactor13** [comment]
> Выпустили исправление на своей стороне, крэшей больше не должно быть. Проверьте пожалуйста в вашем приложении отсутсвие крэшей при загрузке и показе рекламы.

на текущий момент проблема не повторяется. спасибо
