### ISSUE TITLE
Будет ли засчиитан показ при таком рендере рекламы?

### ISSUE THREAD

**Issue by bimawa** [yandexmobile/yandex-ads-sdk-ios#16]
@kanstantsin Здравствуй, Костя. 
Подскажи, пожалуйста, будет ли засчитан показ нативки при таком рендере, как на скине.
Так как тех.долг. не позволяет сделать ресайз ячейки под контент, а рекламное место бывает нужно больше. Можно ли сделать трункейт текста дабы уместить его в 2 строчки? 

![img_5746](https://user-images.githubusercontent.com/1393809/30509730-c9b3093e-9ad0-11e7-8a7c-978a386cd0e2.PNG)

**Comment by kanstantsin** [comment]
Добрый день.
Показ в таком случае засчитаться не должен.  В текущей версии при обрезании текста показ также не будет засчитан, хотя мы думаем над такой возможностью.
Самым правильным решением было бы считать высоту ячейки по содержимому.
Если в данный момент так сделать не получается, то можно немного увеличить статическую высоту ячейки и обрезать текст объявления до 3-х строк, т.к. более длинный текст очень маловероятен.
К тому же, интересно, корректно ли отображается объявление с предупреждением. Проверить можно на демонстрационных блоках, перечисленных в наших примерах на [GitHub](https://github.com/yandexmobile/yandex-ads-sdk-ios/blob/master/Examples/NativeExample/NativeExample/ViewController.m)

**Comment by bimawa** [comment]
Ок, спасибо, большое. Буду пробывать.
