### ISSUE TITLE
 -[YMASKAdImpressionFactory SKAdImpressionWithImpressionData:] crash 

### ISSUE THREAD

**Issue by ilyalatugovskii** [yandexmobile/yandex-ads-sdk-ios#160]
![telegram-cloud-photo-size-2-5235662372339828491-y](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/46156576/e21f9054-916d-4dc1-b5a4-c92532f7e31e)

Xcode 14.3.1
Crash только на IOS 16.0.x
SDK 5.7.0

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 24741911. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp22.06.2023, 13:43, "ilyalatugovskii" ***@***.***>:

Xcode 14.3.1
Crash только на IOS 16.0.x

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за информацию, будем фиксить.

**Comment by Reactor13** [comment]
Такая же проблема.
После настоятельных советов обновить SDK с 5.4.0 на более "стабильную" 5.7.0 получаем такие же крэши.
Последний месяц постоянно возникают те или иные проблемы с SDK.

**Comment by mobile-ads-github** [comment]
Добрый день! Проблема была решена в релизе SDK 5.8.0.
