### ISSUE TITLE
Останавливается воспроизведение аудио при отображении видео рекламы.

### ISSUE THREAD

**Issue by sskurzhanskiy** [yandexmobile/yandex-ads-sdk-ios#161]

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 24898149. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp30.06.2023, 12:23, "sskurzhanskiy" ***@***.***>:

**Comment by mobile-ads-github** [comment]
Здраствуйте. Извините за долгий ответ. Вы можете сделать кастомную настройку аудио через  YMAAudioSessionManager
https://yandex.ru/dev/mobile-ads/doc/ios/ref/Classes/YMAAudioSessionManager.html

YMAAudioSessionManager.html можно достать из YMAMobileAds.audioSessionManager
