### ISSUE TITLE
YandexMobileMetrica, YandexMobileAds break #Preview in Xcode 15, and SwiftUI Preview also in Xcode 14,13...

### ISSUE THREAD

**Issue by iDevPro** [yandexmobile/yandex-ads-sdk-ios#165]
Hello Yandex, could you please fix your libraries for gain previews work again.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25238541. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp13.07.2023, 13:35, "iQQator" ***@***.***>:
Hello Yandex, could you please fix your libraries for gain previews work again.

**Comment by mobile-ads-github** [comment]
Hello! 
Sorry for the late reply.

We are considering the possibility of adding support for Swift UI and the XCode 15' #Preview feature, but this is not in the immediate plans.

**Comment by iDevPro** [comment]
This is not resolve the problem using your library with project, which cannot be debugged with Canvas for SwiftUI preview begin iOS 14+
