### ISSUE TITLE
GAD_GADSizedAdView_arm64_10_3_0 crash

### ISSUE THREAD

**Issue by TimKaldybek** [yandexmobile/yandex-ads-sdk-ios#166]
<img width="688" alt="Снимок экрана 2023-07-14 в 16 23 15" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/34262459/e5733974-dee5-4125-92f8-68a85ff54a53">
<img width="881" alt="Снимок экрана 2023-07-14 в 16 23 52" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/34262459/e2a314fe-b5dc-464a-a4d8-e71c56733ec1">

Crash occurs on different iOS devices with different iOS, starting from 14.0 to 16.0.
Any feedback and progress on this issue will be very grateful. Thank you in advance.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25263618. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 13:26, "TimKaldybek" ***@***.***>:


Crash occurs on different iOS devices with different iOS, starting from 14.0 to 16.0.
Any feedback and progress on this issue will be very grateful. Thank you in advance.

**Comment by mobile-ads-github** [comment]
Hello
Why do you think that this сrash is due to Yandex Ads SDK ? I don't see Yandex methods in your stacktrace. 
I see the 'GAD' prefix. This prefix specific to the GoogleMobileAds SDK, but I couldn't find the GADSizedAdView class in Google SDK. Are you using the GoogleMobileAds SDK?

**Comment by TimKaldybek** [comment]
> 

Yes, we use GoogleMobileAds SDK.
