### ISSUE TITLE
Предупреждения из Security

### ISSUE THREAD

**Issue by iHarnastaeu** [yandexmobile/yandex-ads-sdk-ios#168]
Много предупреждений 
This method should not be called on the main thread as it may lead to UI unresponsiveness.
Xcode-14.2
<img width="472" alt="Screenshot 2023-07-17 at 12 18 24" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/16429560/769f2b45-8b16-4dbe-ab74-93bef13ad218">

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.
Мы уже работаем над этой проблемой.

**Comment by mobile-ads-github** [comment]
эта проблема возникает из-за плохого взаимодействия эпловских фреймворков, мы не можем убрать это предупреждение на своей стороне
https://developer.apple.com/forums/thread/714467?answerId=734799022#734799022
