### ISSUE TITLE
Main thread checker issue (v2.7.2, Xcode 9.0)

### ISSUE THREAD

**Issue by Usipov** [yandexmobile/yandex-ads-sdk-ios#17]
Hello!

We use the latest version of your awesome framework (currently 2.7.2) but face an annoying issue with a main thread checker, which was introduced with Xcode 9 pretty long time ago.

I did not find a similar issue (which was a surprise for me). Sorry if this one is a duplicate...

The following frame interacts with `UIKit` from a background thread, which is not good and makes use of your library pretty annoying:
`[UIScreen(YMAAdditions) yma_sizeForOrientation]`

I'm not sure whether this one is the only case, but I assume it isn't.

This situation is a bit sad =).

Please, fix the issue as soon as possible.
Thanks in advance!

**Comment by kanstantsin** [comment]
Hello!

Thank you for your feedback.
The next release will have the fix for this issue. It has already been solved, just waiting to ship.
We will close the issue as soon as the new version of SDK is deployed.

**Comment by Usipov** [comment]
Nice =)

**Comment by kanstantsin** [comment]
Fixed in 2.8.0
