### ISSUE TITLE
Невозможно собрать демо-приложение.

### ISSUE THREAD

**Issue by ademyanets** [yandexmobile/yandex-ads-sdk-ios#173]
Согласно инструкции мемка не собирается, на выходе 50+ ошибок по поводу раскрытия типов вида
![image](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/1822856/2bf71955-eccd-42eb-bf8a-5ec8e8c12b07)
Xcode 14.3.1 и бета Xcode 15 - один результат. Как заставить все это работать, что-то не попало в инструкцию?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2368. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2368 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Исправлено в [b12b6213cf208f6b1c27f7da6811fecc2e020d0a](https://github.com/yandexmobile/yandex-ads-sdk-ios/commit/b12b6213cf208f6b1c27f7da6811fecc2e020d0a)
