### ISSUE TITLE
invalid custom path 'MobileAdsTarget' for target 'MobileAdsTarget'

### ISSUE THREAD

**Issue by TemaSysoev** [yandexmobile/yandex-ads-sdk-ios#178]
После перехода на версию 6.0 появилась ошибка. Попробовал заново добавить Package – не помогло. Хотел узнать, как решить эту проблему 

Xcode 15.0

**Comment by mobile-ads-github** [comment]
Добрый день, проблему исправили. Попробуйте подключить еще раз, если будет браться версия из кэша, предварительно очистите кэш:
```bash
find ~/Library/Caches/org.swift.swiftpm/repositories -name "yandex-ads-sdk-swift*" -exec rm -rf {} +
```
