### ISSUE TITLE
YMANativeImageAd problem 

### ISSUE THREAD

**Issue by ZalyalovIldar** [yandexmobile/yandex-ads-sdk-ios#18]
Приходит реклама типа YMANativeImageAd, дальше идет кусок кода: 

<img width="568" alt="2017-11-07 12 05 43" src="https://user-images.githubusercontent.com/8490823/32485298-01c02742-c3b4-11e7-9479-b4cb8d911a72.png">

YMANativeImageAdView добавляется на нужное место, в визуальном дебагинге в слоях видно что такая вьюха есть, но при этом на ней нет нужной картинки. 

Так же проверил, что у YMANativeImageAdView imageView не пустой, как и image. 
После того как срабатывает метод loadImages() метод делегата YMANativeAdImageLoadingObserver так же отлавливает завершение загрузки картинок, но картинка не появляется, сама вьюха YMANativeImageAdView не отлавливает тапы. 
Вся нужная информация приходит, картинка и тестовый текст.  
Binding с вьюхой проходит без ошибки, все ок.

Так же если просто добавить на экран imageView, который присвоили для YMANativeImageAdView, то нужная картинка рекламы отображается... 

Подскажите пожалуйста, в чем может быть проблема?

**Comment by kanstantsin** [comment]
Здравствуйте,

Не могли бы Вы дать ссылку на небольшой проект (или приложить его архивом), где можно было бы воспроизвести проблему? Пока не могу сказать, в чем может быть проблема.

**Comment by kanstantsin** [comment]
Нашли проблему в настройках объявления. Поправили. Решена ли Ваша проблема?
В свою очередь добавим валидацию для того, чтобы проблему было проще диагностировать.

**Comment by ZalyalovIldar** [comment]
@kanstantsin к сожалению проблема не решилась( 
Сейчас организую тестовый проект, если так и не заработает.

**Comment by ZalyalovIldar** [comment]
@kanstantsin https://github.com/ZalyalovIldar/YMANativeImageAdTestProj/

**Comment by ZalyalovIldar** [comment]
В консоли конечно выходит ошибка связанная с потоками, но вроде бы тут уже было issue на эту тему или подобную...

<img width="383" alt="2017-11-08 16 12 35" src="https://user-images.githubusercontent.com/8490823/32550873-b0aa514c-c49f-11e7-8a60-b868dca0d32b.png">

**Comment by kanstantsin** [comment]
UIImageView создается, но в иерархию не добавляется.
В тестовом проекте, если после 74-й строки файла `YandexAdFoxViewBuilderImplementation.swift` добавить строку 

```nativeImageAdView.addSubview(nativeImageView)```

то баннер отображается.

Посмотреть можно в моем форке: https://github.com/kanstantsin/YMANativeImageAdTestProj/blob/FIX/TestProject/Ad%20Manager/YandexAdFoxViewBuilderImplementation.swift#L77

**Comment by ZalyalovIldar** [comment]
вот это поворот, думал при биндинге уже внутри само как нужно встает. 
Может пометку где сделать в доках или еще, не очень очевидный момент)

Спасибо за помощь.)
