### ISSUE TITLE
Version 6.1.0 MobileAdsBundle.bundle is not added with Cocoapods use_frameworks! :linkage => :static

### ISSUE THREAD

**Issue by Str4tos** [yandexmobile/yandex-ads-sdk-ios#181]
Добрый день. 
Интегрирую Yandex Mobile Ads 6.1.0 с помощью Cocoapods.  
И получаю ошибку интеграции:
```
[Integration] MobileAdsBundle.bundle is not added. Make sure that bundle was added to the Copy Bundle Resource phase
```

Проблема происходит когда: 
1. Xcode проект состоит из App target и Dynamic Framework Target, например как Unity App.  
2. Cocoapods зависимости интегрируются в Dynamic Framework Target, а не в App Target.
3. Podfile имеет строку `use_frameworks! :linkage => :static` для статической линковки зависимостей.

В этом случае код и `Resources.bundle` зависимых фреймворков добавляется в Dynamic Framework.
<img width="283" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/22005013/8327facd-4eba-4dfe-b4a1-40ba048cd746">

Но Yandex Ads Framework ищет `MobileAdsBundle.bundle` только в `Bundle.main`.
Возможно стоит искать `MobileAdsBundle.bundle` примерно следующим кодом:
```swift
// Bundle в котором лежит код Yandex Mobile Ads Framework
if let path = Bundle(for:YMAMobileAds.self).path(forResource:"MobileAdsBundle", ofType: "bundle") {
   return Bundle(path: path)
}
// Main Bundle приложения
if let path = Bundle.main.path(forResource:"MobileAdsBundle", ofType: "bundle") {
   return Bundle(path: path)
}
```

Понимаю, что я могу добавить `MobileAdsBundle.bundle` в Copy Bundle Resource phase для App target, но лучше учитывать такую ситуацию в Framework который ищет свои ресурсы.

Спасибо

**Comment by mobile-ads-github** [comment]
Проверим возможность такой реализации. При положительном исходе, текущее ишью будет прилинковану к релизу с фиксом.
