### ISSUE TITLE
Пожалуйста не перезаписывайте подспеки без смены версии

### ISSUE THREAD

**Issue by kattouf** [yandexmobile/yandex-ads-sdk-ios#184]
<img width="1161" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/7829589/e23db966-4488-4463-857e-8f1cf9911363">

https://github.com/search?q=repo%3ACocoaPods%2FSpecs+YandexMobileAds&type=commits

По моим наблюдениям Cocoapods устроен так, что если версия podspec не поменялась, он не подтягивает ее новую версию, даже если там поменялся перечень зависимостей или их версии

Поэтому когда происходит перезатирание подспек не меняя версию, машины которые успели спулить подспек для версии, не получают обновления этой версии до тех пор, пока вручную не удалят кеши репозитория подспеков. 
По итогу у разных разработчиков могут быть разные версии и при инстале подов они получают разные хеши в лок файле.
Помимо этого часть разработчиков все равно не получает ваши фиксы, если успели уже забрать сломанный спек.

В общем мое предложение и пожелание всегда делать инкремент версии при изменениях в podspec

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2620. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2620 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
В дальнейшем пре подобных проблемах будем поднимать патч.
