### ISSUE TITLE
Сломана поддержка подключения через SPM

### ISSUE THREAD

**Issue by Kotenagitare** [yandexmobile/yandex-ads-sdk-ios#185]
Подключаю YandexMobileAds по инструкции из свежей документации.

Получаю ошибку линковки.

Может ли это быть из-за того, что Divkit ожидает VGSL версии 2.2.0, а подключается версия 2.4.1 а проект?

<img width="454" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/38511910/bf523f86-d614-4789-94bd-07077d0b5767">

<img width="231" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/38511910/b8728f57-69c5-4018-83d2-d5f9fd0dceaa">

Лог ошибки:

lld: warning: Could not find or use auto-linked framework 'MACPlatformDescription'
ld: warning: Could not find or use auto-linked framework 'MACLogging'
ld: warning: Could not find or use auto-linked framework 'MACAnalytics'
ld: warning: Could not find or use auto-linked framework 'MACHeaderBidding'
ld: warning: Could not find or use auto-linked framework 'MACFeatureFlags'
ld: warning: Could not find or use auto-linked framework 'MACSDKConfiguration'
ld: warning: Could not find or use auto-linked framework 'MACNetworking'
ld: warning: Could not find or use auto-linked framework 'MACBaseUI'
ld: warning: Could not find or use auto-linked framework 'MACVASTKit'
ld: warning: Could not find or use auto-linked framework 'MACMediation'
ld: warning: Could not find or use auto-linked framework 'MACConstants'
ld: warning: Could not find or use auto-linked framework 'MACConsent'
ld: warning: Could not find or use auto-linked framework 'MACBase'
ld: warning: Could not find or use auto-linked framework 'MACDependenciesUmbrella'
ld: warning: Could not find or use auto-linked framework 'MACEncryption'
ld: warning: Could not find or use auto-linked framework 'MACCAChallengeHandler'
Undefined symbols for architecture arm64:
  "_$s10BasePublic11ImageHolderPAAE07requestC10WithSourceyAA11Cancellable_pSgySo7UIImageC_AA16URLRequestResultV0G0OtSgcF", referenced from:
      _$s15YandexMobileAds21AdDivLocalImageHolderC10BasePublic0gH0AadEP07requestG10WithSourceyAD11Cancellable_pSgySo7UIImageC_AD16URLRequestResultV0M0OtSgcFTW in YandexMobileAds(AdDivLocalImageHolder.o)
  "_$s14BaseTinyPublic6TaggedV8rawValueACyxq_Gq__tcfC", referenced from:
      _$s15YandexMobileAds6cardId33_871BCAF4ECD08C108C4B1E597886F8F3LL_WZ in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6DivKit0A20BlockModelingContextV6cardId0f3LogG010parentPath0ia5StateJ012stateManager05blockK7Storage17visibilityCounter22lastVisibleBoundsCache18imageHolderFactory017highPriorityImagewX009divCustomcX012fontProvider9flagsInfo17extensionHandlers0L12Interceptors09variablesO006playerX011debugParams9scheduler23childrenA11yDescription0I10ScrollView06errorsO015layoutDirection15variableTracker016persistentValuesO0011tooltipViewX0AC14BaseTinyPublic6TaggedVyAA9CardIDTagOSSG_SSSg06LayoutB9Interface09UIElementJ0VSgA4_yAA0akJ3TagOA11_GSgAA0akM0CAA0ackO0CAA0A18VisibilityCounting_pSgAA0a4LaststU0CSg16NetworkingPublic05ImagewX0VA28_SgAA0a6CustomcX0_pSgAA0A12FontProvider_pSgAA0A9FlagsInfoVSayAA0A16ExtensionHandler_pGSayAA0aK11Interceptor_pGAA0a9VariablesO0C06LayoutB006PlayerX0_pSgAA11DebugParamsV10BasePublic10Scheduling_pSgA8_A47_14ScrollViewType_So6UIViewCXcSgAA0a6ErrorsO0CSgSo30UIUserInterfaceLayoutDirectionVAA0A15VariableTrackerCSgAA0a16PersistentValuesO0CSg16CommonCorePublic0sT8Tracking_A52_XcAA0A0OcSgtcfC", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$s6DivKit11DebugParamsV02isC11InfoEnabled19processMeasurements04showcF018errorCounterInsetsACSb_y14BaseTinyPublic6TaggedVyAA9CardIDTagOSSG6cardId_AC0I0V12measurementst_tcySo6UIViewCcSo06UIEdgeM0VtcfC", referenced from:
      _$s15YandexMobileAds30DivBlockModelingContextFactoryC4make02adD18LocalImageProvider0D3Kit0defG0VAA02AddklM0C_tF in YandexMobileAds(DivBlockModelingContextFactory.o)
  "_$ss6ResultO10BasePublicE9isSuccessSbvg", referenced from:
      _$s15YandexMobileAds23AdDivMediaBlockProviderC06customG04data7context9LayoutKit0G0_p0eM00E10CustomDataV_AI0eG15ModelingContextVtF in YandexMobileAds(AdDivMediaBlockProvider.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mobile-ads-github** [comment]
Да, это связанно именно с этим. Перевыпустили релиз [spm 6.1.0](https://github.com/yandexmobile/yandex-ads-sdk-swift/releases/tag/6.1.0).

**Comment by Kotenagitare** [comment]
Сбросил кэш и перекачал, версии остались теми же, проблема сохраняется.

**Comment by mobile-ads-github** [comment]
Какая версия vgsl подтягивается?

**Comment by Kotenagitare** [comment]
2.4.1

**Comment by mobile-ads-github** [comment]
Веорятно, кэш не почищен: помимо локально, проверьте глобалный: ` ~/.swiftpm/cache/repositories/yandex-ads-sdk-swift-<sha>`.

**Comment by Kotenagitare** [comment]
Очистил глобальный. Версия всё равно 2.4.1

**Comment by mobile-ads-github** [comment]
Попробуйте почиcтить `~/.swiftpm` полностью

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2646. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2646 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
