### ISSUE TITLE
Утечки памяти.

### ISSUE THREAD

**Issue by kotsan777** [yandexmobile/yandex-ads-sdk-ios#188]
Происходит утечка памяти при работе с YMANativeAdLoader

Также происходит утечка памяти  при запросе вызове метода -[YMANativeAdLoader loadAdWithRequestConfiguration:]
Разобравшись с вопросом было выявлено, что в этом также замешан [Firebase Performance ](https://firebase.google.com/docs/perf-mon)

Firebase Performance изменяет инициализацию URLSession, чтобы настроить прокси-сервер делегата для получения показателей о запросах.
Если делегат настроен для экземпляра URLSession, то для предотвращения утечек памяти необходимо вызвать метод validateAndCancel или FinishTasksAndInvalidate. 
[Источник](https://github.com/firebase/firebase-ios-sdk/issues/8277)

Я предполагаю, что часть утечек происходит из-за того, что не вызываются методы validateAndCancel или FinishTasksAndInvalidate в YMANativeAdLoader, который использует URLSession.

Утечка памяти в связке Yandex-Ads-SDK + Firebase Performance
![image](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/88779323/b825272d-9ed5-44fa-acc8-7761a0910fb4)

Утечка памяти с использованием Yandex-Ads-SDK без Firebase Performance
![image](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/88779323/9cbcac86-84ec-437b-8152-b343ff4b8606)

**Comment by kotsan777** [comment]
Здравствуйте, есть актуальная информация?

**Comment by mobile-ads-github** [comment]
Здравствуйте! Спасибо за информацию! Смотрим на своей стороне - если проблема подтвердится исправим в ближайшем релизе

**Comment by iDevPro** [comment]
Так-же имею данную проблему

**Comment by iDevPro** [comment]
![Снимок экрана 2024-03-16 в 18 34 41](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/1888230/4a7bab72-e975-4e37-bd38-c46dcf94788a)
Обновился до последней версии, не помогло :(

**Comment by mobile-ads-github** [comment]
Добрый день! Исправим в ближайшем обновлении

**Comment by TimKaldybek** [comment]
> Добрый день! Исправим в ближайшем обновлении

Хотелось бы узнать, когда планируемая дата релиза ближайшего обновления?

**Comment by Ilik777** [comment]
Добрый день! Аналогичная проблема, подскажите статус

**Comment by mobile-ads-github** [comment]
Исправлено в [Релизе 7.1.0](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/tag/7.1.0)
