### ISSUE TITLE
YandexMobileAds 6.2.0 SPM integration.  Не работает показ interstitial ad, всегда падает в ошибку "Incorrect fullscreen view."

### ISSUE THREAD

**Issue by klenovdev** [yandexmobile/yandex-ads-sdk-ios#189]
YandexMobileAds 6.2.0 SPM integration.  
Не работает показ interstitial ad, всегда падает в ошибку "Incorrect fullscreen view."

Для проверки использовал код из вашего демо проекта

```
private lazy var presentButton: UIButton = {
        let button = UIButton(
            configuration: .tinted(),
            primaryAction: UIAction(title: "Present ad") { [weak self] _ in
                guard let self else { return }
                self.interstitialAd?.show(from: self)
                self.presentButton.isEnabled = false
            }
        )
        button.translatesAutoresizingMaskIntoConstraints = false
        button.setTitle("Present ad", for: .normal)
        button.isEnabled = false
        return button
    }()
```

В итоге в делегате получаю ошибку: "Incorrect fullscreen view."

```
func interstitialAd(_ interstitialAd: YMAInterstitialAd, didFailToShowWithError error: Error) {
        print("\(makeMessageDescription(interstitialAd)) failed to show. Error: \(error)")
 }
```
 
 В версии 6.1.0 таких проблем нет.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2710. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2710 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Данный баг был исправлен в Yandex Mobile Ads SDK 6.3.0. Попробуйте установить эту версию.

**Comment by klenovdev** [comment]
Здравствуйте, да заработало, спасибо.
