### ISSUE TITLE
Прерывается воспроизведение аудио из-за видеорекламы

### ISSUE THREAD

**Issue by kotsan777** [yandexmobile/yandex-ads-sdk-ios#192]
Прерывается воспроизведение аудио из-за видеорекламы при ее появлении на экране.

Пытался решить проблему с помощью [YMAAudioSessionManager](https://yandex.ru/dev/mobile-ads/doc/ios/ref/Classes/YMAAudioSessionManager.html)

Выставление значения YMAAudioSessionManager.isAutomaticallyManaged = true частично решает проблему.
Аудио в таком случае прерывается только один раз. При последующих показах видеорекламы аудио не прерывается.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2786. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2786 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Вам необходимо выставить YMAMobileAds.audioSessionManager().isAutomaticallyManaged = false и установить для него делегат YMAAudioSessionManagerDelegate, в котором вы можете задать необходимое поведение.

**Comment by mobile-ads-github** [comment]
Также обнаружили проблему на нашей стороне, исправим в следующем релизе.

**Comment by mobile-ads-github** [comment]
Исправлено в [6.4.0](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/tag/6.4.0)
