### ISSUE TITLE
Interstitial ad error to show.

### ISSUE THREAD

**Issue by signallabsoftware** [yandexmobile/yandex-ads-sdk-ios#193]
Hello,
Currently I using version 6.2.3, ad loaded successful but can not show. How to fix this error?
Error: Error Domain=com.mobile.ads.MobileAdsCore Code=10 \"Incorrect fullscreen view.\" UserInfo={NSLocalizedDescription=Incorrect fullscreen view.}"

**Comment by mobile-ads-github** [comment]
Hello! Can you specify which version of the SDK you are using? We did not release version 6.2.3.

**Comment by signallabsoftware** [comment]
I using vesion 6.2.0 and Xcode 14.2 I started with guide https://yandex.com/dev/mobile-ads/doc/ios/quick-start/ios-ads-component.html
https://github.com/yandexmobile/yandex-ads-sdk-swift
I don't use this repository because Xcode 14.2 that does not support 6.3.0

**Comment by mobile-ads-github** [comment]
Can you attach charles session with this error. Or if it is impossible provide your app bundle. We will try to find, what's going wrong in our logs.
