### ISSUE TITLE
Креши из-за использования UIGraphicsBeginImageContext в iOS 17

### ISSUE THREAD

**Issue by CroperMR** [yandexmobile/yandex-ads-sdk-ios#194]
<img width="1067" alt="Screenshot 2024-01-25 at 16 16 19" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/26144373/1174f414-0ac2-4c2c-9066-dbcdf489d56f">

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2847. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2847 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Советуем обновить версию SDK, т.к данный код больше не используется.

**Comment by CWftw** [comment]
For those of us with apps in production on 5.x, we seem to be getting a spike of these crashes yesterday and today. Is there anything we can do to mitigate them?

**Comment by mobile-ads-github** [comment]
We only reproduced this crash when calling our banner API with a zero size (height, width or both) on ios 17+. Make sure you never pass a zero size to the Banne API.
We made this case safe in sdk 6.3.0, but we can’t do anything for previous versions.

**Comment by thomasmso** [comment]
@mobile-ads-github - which "banner API" are you referring to?

**Comment by mobile-ads-github** [comment]
@thomasmso 
YMABannerAdSize
We reproduced this crash when creating a YMABannerAdSize with a zero size. There may be other ways to reproduce this crash, but we haven't found any.
We have removed the problematic code in SDK 6.3.0
