### ISSUE TITLE
При установке сразу же ошибка! Zip3Sequence

### ISSUE THREAD

**Issue by Kabudasay** [yandexmobile/yandex-ads-sdk-ios#198]
![Monosnap NskAdsSDK — Zip3 swift 2024-02-27 20-10-56](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/11681789/8f1fb59d-b8e0-4013-830a-12ecd993b750)

Вот под

platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

pod 'GoogleAds-IMA-iOS-SDK', '~> 3.20.0'
pod 'YandexMobileAds'
pod 'YandexMobileAdsInstream'

deployment_target = '13.0'

post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
      end
      project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
    end
end

**Comment by mobile-ads-github** [comment]
Попробуйте выставить `BUILD_LIBRARY_FOR_DISTRIBUTION=NO` для `DivKit`. Примеры можно посмотреть в https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/175 [здесь](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/175#issuecomment-1735743164) и [здесь](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/175#issuecomment-1755489255).

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2978. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2978 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by canitakeyourecode** [comment]
https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/198#issuecomment-1967252500

указывал в под файле при установке не помогло

**Comment by mobile-ads-github** [comment]
Thank you for reaching out.
I am on a business trip till March 8. Please expect some delay in reply.

**Comment by mobile-ads-github** [comment]
Эта ошибка происходит не при компиляции DivKit, а при компиляции ее транзитивных зависимостей, а именно: `VGSL_Fundamentals_tiny`. Необходимо выключить `BUILD_LIBRARY_FOR_DISTRIBUTION` для его и зависимостей. В [этом комментарии](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/175#issuecomment-1735743164) есть пример кода, который необходимо добавить.

Если интересует быстрый вариант, то

```ruby
pod_targets_for_disable_build_for_distribution = [
     'VGSL_Fundamentals_tiny', # сюда необходимо будет добавлять имена тех библиотек, в которых появляется подобная ошибка
]

post_install do |installer|
     if target.name.start_with?(*pod_targets_for_disable_build_for_distribution)
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        end
    end
end 
```

**Comment by canitakeyourecode** [comment]
Вот что ловлю


ld: Undefined symbols:
  static LayoutKitInterface.UIElementPath.__derived_struct_equals(LayoutKitInterface.UIElementPath, LayoutKitInterface.UIElementPath) -> Swift.Bool, referenced from:
      generic specialization <serialized, LayoutKitInterface.UIElementPath> of Swift.__RawDictionaryStorage.find<A where A: Swift.Hashable>(_: A, hashValue: Swift.Int) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) in YandexMobileAds[arm64][768](DivBlockModelingContextFactory.o)
      generic specialization <serialized, LayoutKitInterface.UIElementPath> of Swift.__RawDictionaryStorage.find<A where A: Swift.Hashable>(_: A, hashValue: Swift.Int) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) in YandexMobileAds[arm64][768](DivBlockModelingContextFactory.o)
      generic specialization <serialized, LayoutKitInterface.UIElementPath> of Swift.__RawDictionaryStorage.find<A where A: Swift.Hashable>(_: A, hashValue: Swift.Int) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) in YandexMobileAds[arm64][768](DivBlockModelingContextFactory.o)
  DivKit.DivFlagsInfo.default.unsafeMutableAddressor : DivKit.DivFlagsInfo, referenced from:
      YandexMobileAds.DivBlockModelingContextFactory.make(adDivLocalImageProvider: YandexMobileAds.AdDivLocalImageProvider) -> DivKit.DivBlockModelingContext in YandexMobileAds[arm64][768](DivBlockModelingContextFactory.o)
  static LayoutKit.LayoutTrait.__derived_enum_equals(LayoutKit.LayoutTrait, LayoutKit.LayoutTrait) -> Swift.Bool, referenced from:
      static YandexMobileAds.AdDivCustomBlock.== infix(YandexMobileAds.AdDivCustomBlock<A>, YandexMobileAds.AdDivCustomBlock<A>) -> Swift.Bool in YandexMobileAds[arm64][758](AdDivCustomBlock.o)
      static YandexMobileAds.AdDivCustomBlock.== infix(YandexMobileAds.AdDivCustomBlock<A>, YandexMobileAds.AdDivCustomBlock<A>) -> Swift.Bool in YandexMobileAds[arm64][758](AdDivCustomBlock.o)
      protocol witness for static Swift.Equatable.== infix(A, A) -> Swift.Bool in conformance YandexMobileAds.AdDivCustomBlockHeight : Swift.Equatable in YandexMobileAds in YandexMobileAds[arm64][761](AdDivCustomBlockHeight.o)
  LayoutKit.LayoutTrait.Weight.default.unsafeMutableAddressor : LayoutKit.LayoutTrait.Weight, referenced from:
      YandexMobileAds.AdDivCustomBlock.weightOfVerticallyResizableBlock.getter : LayoutKit.LayoutTrait.Weight in YandexMobileAds[arm64][758](AdDivCustomBlock.o)
      YandexMobileAds.AdDivCustomBlockFactory.makeBlock(data: DivKit.DivCustomData, context: DivKit.DivBlockModelingContext) -> LayoutKit.Block in YandexMobileAds[arm64][760](AdDivCustomBlockFactory.o)
      YandexMobileAds.AdDivMediaBlockProvider.customBlock(data: DivKit.DivCustomData, context: DivKit.DivBlockModelingContext) -> LayoutKit.Block in YandexMobileAds[arm64][763](AdDivMediaBlockProvider.o)
      YandexMobileAds.AdDivMediaBlockProvider.(createAdDivMediaCustomBlockWithAspectRatio in _08BC3DF69D1A746CA846FB6064E5EF82)(adDivProperties: YandexMobileAds.AdDivProperties, data: [Swift.String : Any]) -> Swift.Result<YandexMobileAds.AdDivCustomBlock<YandexMobileAds.AdDivMediaBlockViewImpl>, YandexMobileAds.AdDivKitError> in YandexMobileAds[arm64][763](AdDivMediaBlockProvider.o)
      YandexMobileAds.AdDivProgressBlockProvider.customBlock(data: DivKit.DivCustomData, context: DivKit.DivBlockModelingContext) -> LayoutKit.Block in YandexMobileAds[arm64][765](AdDivProgressBlockProvider.o)
  direct field offset for LayoutKit.UIActionEvent.uiAction : LayoutKitInterface.UserInterfaceAction, referenced from:
      YandexMobileAds.DivKitViewActionHandlerImpl.handle(event: LayoutKit.UIActionEvent, divKitView: YandexMobileAds.DivKitView) -> () in YandexMobileAds[arm64][781](DivKitViewActionHandler.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by canitakeyourecode** [comment]
А это с чем связано ?

**Comment by Kabudasay** [comment]
?

**Comment by Kabudasay** [comment]
так а ответ будет ?

**Comment by canitakeyourecode** [comment]
Подскажите долго ли ждать ответа ? 
Я сделал как вы сказали а по итогу так и не работает

**Comment by mobile-ads-github** [comment]
Попробуйте повторить ответ из [этого комментария](https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/205#issuecomment-2069299705):

В `Podfile` необходимо указывать поды для тех таргетов, в которых их будете непосредственно использовать, а также:

* `pod_targets_for_disable_build_for_distribution` должны включать ВСЕ транзитивные зависимости `DivKit`  
*  явно указать `use_frameworks! :linkage => :static `

Лучше всего иметь скрипт, который по имени пода будет собирать все его транзитивные зависимости - и уже для них отключать `BUILD_LIBRARY_FOR_DISTRIBUTION`, но как временное решение,  можно указать все явно:

```ruby
pod_targets_for_disable_build_for_distribution = [
  'DivKit',
  'DivKit_LayoutKit',
  'DivKit_LayoutKitInterface',
  'DivKit_Serialization',
  'VGSL_Fundamentals',
  'VGSL_Fundamentals_Tiny',
  'VGSLBase',
  'VGSLBaseTiny',
  'VGSLBaseUI',
  'VGSLCommonCore',
  'VGSLNetworking',
]
```

**Comment by Kabudasay** [comment]
не понимаю зачем мне явно указывать
 use_frameworks! :linkage => :static 

Ну а pod_targets_for_disable_build_for_distribution это не сработает так как я просто тупо его выключал для всего, я ж скинул вам пример на github

**Comment by mobile-ads-github** [comment]
`use_frameworks! :linkage => :static` для удаления дублирования таргетов про проекте `Pods` вида: `<target_name>-framework` `<target_name>-library`.

Именно с этими изменениями ваш пример и был успешно собран.

**Comment by Kabudasay** [comment]
Так я после собираю в framework  скриптом

**Comment by mobile-ads-github** [comment]
В чем разница сборки скриптом и через UI в Xcode?

**Comment by Kabudasay** [comment]
Разница в том что что я собираю fat либу

**Comment by mobile-ads-github** [comment]
Что включено в `fat либу`? Динамическая/статическая версия фрэймворка либо разные типы таргетов?

**Comment by Kabudasay** [comment]
не не я собираю под arm и x86

**Comment by mobile-ads-github** [comment]
По-итогу получилось ли собрать?
