### ISSUE TITLE
Проблема сборки на не ARM машинах. 

### ISSUE THREAD

**Issue by Feskoxoxo** [yandexmobile/yandex-ads-sdk-ios#199]
<img width="317" alt="Screenshot 2024-03-04 at 18 18 12" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/14035027/5bc1ff26-a7a4-4b03-bb0b-b3d289effe90">
![image](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/14035027/6b90cedd-06a5-443e-abe4-0ff649c2543e)

Задача: собирать сборку на компьютерах не с ARM процессорами. 
Системные характеристики: 
Mac mini
Intel Core i3
3.6 GHz
8гб
OS На текущий момент mac os Venture 13.5
Xcode 14.2

Текущая версия библиотеки: 6.4.0
Последняя версия библиотеки, где сборка была завершена успешно: 6.2.0

тестовый проект https://github.com/Feskoxoxo/TestYandexADSPRoject

Также не работает и проект из Examples

Успешно проходит сборка на машине с m1.
С Xcode 14.2 и Venture 13.5

Хотелось бы уточнить, минимальные требования для успешной сборки. А также иметь возможность собирать на компьютерах с не ARM процессорами.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2999. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2999 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Подскажите, появляется ли такая ошибка при использовании Xcode 15?

**Comment by Feskoxoxo** [comment]
На текущий момент нет возможности проверить на версии Xcode 15 на не ARM процессорах.
А подскажите пожалуйста, а где можно посмотреть минимальные требования для систем? 
Минимальные требования могу отличаться в зависимости ARM и не ARM. Процессоры?

**Comment by mobile-ads-github** [comment]
Касательно ошибки `Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56`: пробовали ли вы собрать с Xcode 14.3?
Описание есть в [Xcode 14.2. How to correctly change dynamic pod library to static?](https://github.com/CocoaPods/CocoaPods/issues/11960)

**Comment by Feskoxoxo** [comment]
Нет, так же не было возможности обновить.
Но на текущий момент обновились на последний xcode. Там сборка проходит без проблем.
