### ISSUE TITLE
Ads in TableView  (Impression could not be tracked)

### ISSUE THREAD

**Issue by IrixVol** [yandexmobile/yandex-ads-sdk-ios#2]
Добрый день. Я использую стандартный пример YandexMobileAds для таблицы.
Если метод 
`[[YMANativeAdLoaderConfiguration alloc] initWithBlockID:@"R-M-DEMO-native-c" imageSizes:@[ kYMANativeImageSizeLarge ] loadImagesAutomatically:NO];`
вызывается с параметром  `loadImagesAutomatically:NO` то я вижу предупреждение:
`com.yandex.mobile.ads.sdk[40598] <Warning>: Impression could not be tracked. Will attempt to track impression later. Error: Required asset is not visible in ad view: (null)
`

Насколько я понимаю, в таблицах не желательно использовать автоматическую загрузку имиджей. Загрузка происходит при показе ячейки. 

Как сделать чтобы указанное сообщение не появлялось, либо можно ли его игнорировать без опасения, что показы не будут защитаны ?
Заранее спасибо!

![yandexmobileads](https://cloud.githubusercontent.com/assets/5245682/16389986/92278c98-3cb1-11e6-89b4-deb407f1d98a.png)

**Comment by kanstantsin** [comment]
Добрый день.
Все верно. Как сказано в сообщении, попытка засчитать показ будет произведена позже. В случае, если с размещением элементов все хорошо, то в консоли появится сообщение 
```Ad binding successful```
Эта информация отладочная, она выводиться не будет, если не вызывать ```[YMAMobileAds enableLogging]```. В примере этот вызов находится в классе ```AppDelegate```.

**Comment by IrixVol** [comment]
Да `Ad binding successful` выводится! Спасибо за ответ, не ожидала такой быстрой реакции от вас,  здорово! 
Интересно, пробовал ли кто-ли использовать YandexMobileAds для ComponentKit,
это библиотека (разработанная Facebook) для отображения новостной ленты,  представляет из себя CollectionController с ассинхроным выводом компонентов.
Надеюсь все будет считаться и показываться правильно, работает по аналогии с таблицей и сообщения в отладчике такие же выдает (по поводу рекламы).

**Comment by kanstantsin** [comment]
Рад помочь.
Отзывов про использование с ComponentKit не поступало, по этому вопросу не могу ничего сказать.
