### ISSUE TITLE
No BitCode support in 2.8.1

### ISSUE THREAD

**Issue by OneSman7** [yandexmobile/yandex-ads-sdk-ios#20]
All of a sudden :(

`ld: bitcode bundle could not be generated because '-/Pods/YandexMobileAds/dynamic/YandexMobileAds.framework/YandexMobileAds' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '-/Pods/YandexMobileAds/dynamic/YandexMobileAds.framework/YandexMobileAds' for architecture arm64`

**Comment by kanstantsin** [comment]
Thank you for the report!

That's a bug. We'll try to fix it as soon as possible. Meanwhile, please, use 2.8.0 until we fix it.

**Comment by kanstantsin** [comment]
Please, check 2.8.2, the issue should be fixed.

**Comment by OneSman7** [comment]
Yes, 2.8.2 builds ok. No Bitcode warnings. Closing issue.

**Comment by kried** [comment]
Thank you for the report and sorry for inconvenience again.

We'll fix it as soon as possible and make sure the bug does not happen again. Please, use 2.8.2 until we fix it.

**Comment by kried** [comment]
Please, check 2.8.4, the issue should be fixed.
