### ISSUE TITLE
SwiftUI Support

### ISSUE THREAD

**Issue by BadJujuKiss** [yandexmobile/yandex-ads-sdk-ios#202]
Добрый день! На дворе 2024 год, а поддержки SwiftUI все еще нет. У аппловина хотя бы инструкция есть https://dash.applovin.com/documentation/mediation/ios/ad-formats/swiftui. Кажется, уже на SwiftUI пишет большинство. Хочется монетизировать бесплатную версию приложения. Если для межстроничника еще понятна как сделать бридж, то в случае с банерной и нативной рекламой совсем не ясно. Можете хотя бы краткий туториал в документации сделать?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3015. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3015 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by BadJujuKiss** [comment]
> Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3015. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.
> 
> Thank you for your message, a task with the number PCODESUP-3015 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

День добрый. Уже прошло больше двух дней, прокомментируете ситуацию вокруг SwiftUI?

**Comment by mobile-ads-github** [comment]
Здравстуйте, спасибо за ожидание! Изучили вопрос, в ближайшее время добавление поддержки SwiftUI не планируется. Подумаем над возможностью сделать инструкцию.
