### ISSUE TITLE
Не отрабатывают методы делегата YMANativeAdDelegate

### ISSUE THREAD

**Issue by blashkin** [yandexmobile/yandex-ads-sdk-ios#207]
Заметил такую особенность, если один объект реализует одновременно YMANativeAdDelegate и YMANativeAdLoaderDelegate, то методы делегата YMANativeAdDelegate не вызываются. Тестировал на вашем примере:

1. AdFoxNativeViewController
2. NativeCustomViewController
3. NativeTemplateViewController

Опять же, это только догадка, в своем проекте столкнулся с такой же проблемой

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3057. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3057 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за обращение! Нам известна эта проблема, пофиксим в ближайшем релизе.

**Comment by mobile-ads-github** [comment]
Исправлено в [версии 7.0.0](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/tag/7.0.0)
