### ISSUE TITLE
Ограничение рекламы по возрасту

### ISSUE THREAD

**Issue by mobileapps23** [yandexmobile/yandex-ads-sdk-ios#208]
Добрый день! Можно ли настроить выдачу рекламы по возрасту из приложения? Приложение маркировано как 4+ в Аппстор, выдача рекламы включает 18+. Вносим вручную в блок лист домены, но это не очень помогает. Настройка запроса через **requestConfiguration.age = 4**
```
let requestConfiguration = YMAMutableNativeAdRequestConfiguration(adUnitID: self.adNativeUnit)
        requestConfiguration.shouldLoadImagesAutomatically = true
        requestConfiguration.adTheme = .light
        requestConfiguration.age = 4
        
        self.adLoader = YMANativeBulkAdLoader()
        self.adLoader.delegate = self
        self.adLoader.loadAds(with: requestConfiguration, adsCount: adCount)
```
так же не помогает

YandexMobileAds 6.4.1
YandexMobileAdsInstream 0.25.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3072. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3072 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день. На данный момент в SDK нет такой функциональности.
