### ISSUE TITLE
YMANativeBulkAdLoader возвращает массив одинаковых YMANativeAd

### ISSUE THREAD

**Issue by mobileapps23** [yandexmobile/yandex-ads-sdk-ios#209]
Добрый день! При загрузке нескольких рекламных объявлений приходят абсолютно одинаковые

YandexMobileAds 6.4.1
YandexMobileAdsInstream 0.25.0
```
var nativeAds = [YMANativeAd?]()
var adLoader: YMANativeBulkAdLoader!

func loadNativeAd(adCount: Int) {
        if adCount == 0 { return }
        let requestConfiguration = YMAMutableNativeAdRequestConfiguration(adUnitID: self.adNativeUnit)
        requestConfiguration.shouldLoadImagesAutomatically = true
        requestConfiguration.adTheme = .light
        requestConfiguration.age = 4
        
        self.adLoader = YMANativeBulkAdLoader()
        self.adLoader.delegate = self
        self.adLoader.loadAds(with: requestConfiguration, adsCount: adCount)
    }

func nativeBulkAdLoader(_ nativeBulkAdLoader: YMANativeBulkAdLoader, didLoad ads: [YMANativeAd]) {
        // ads - массив одинаковых YMANativeAd
    }
```

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за обращение, в следующем релизе проблема будет решена.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3071. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3071 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Исправлено в [Релизе 7.0.0](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/tag/7.0.0)
