### ISSUE TITLE
YMAAdView not called delegate methods

### ISSUE THREAD

**Issue by Xcdmau5** [yandexmobile/yandex-ads-sdk-ios#21]
Hi, 
I tried to integrate Yandex banner ad in my app. For testing I'm using "R-M-DEMO-320x50" block id. 
After I called loadAd() func nothing happens,  YMAAdViewDelegate methods haven't called.
What problem can be in my situation? A interstitial ad works fine!

 ```
                   let size = YMAAdSize.flexibleSize(with: view.frame.size)
                    self.banner = YMAAdView(blockID: self.getYMABannerIdAd(),
                                           adSize: size,
                                           delegate: self)    
                    banner!.loadAd()
```

**Comment by kanstantsin** [comment]
Hi!
The piece of code you provided looks fine. The best way to find out what's wrong is if you could create a simple project reproducing the issue and post a link to it, so we could debug it.

**Comment by Xcdmau5** [comment]
Hi,
sorry about late answer! Here is project: https://github.com/Xcdmau5/simpleYMA.git

**Comment by kried** [comment]
Hi.
I can see one problem in your sample project. You did not keep strong reference to the instance of YMAAdView, so nothing keeps it from deallocating before ad is loaded.

To solve your problem you should change this line
` weak var banner: YMAAdView?`
to
`var banner: YMAAdView?`
And then delegate methods will be called.

**Comment by Xcdmau5** [comment]
Thank you so much! It works.
