### ISSUE TITLE
Как интегрировать в SwiftUI проект ?

### ISSUE THREAD

**Issue by flashfoxter** [yandexmobile/yandex-ads-sdk-ios#210]
Как интегрировать в SwiftUI проект ?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3081. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3081 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день. В данный момент мы не поддерживаем SwiftUI и у нас нет проверенного способа интеграции, который мы могли бы рекомендовать.
