### ISSUE TITLE
На версии 7.0.0 при вызове loadImages() у NativeAd краш

### ISSUE THREAD

**Issue by Krosdir** [yandexmobile/yandex-ads-sdk-ios#213]
При миграции на версию 7.0.0 (YandexMobileAdsInstream 0.26.0), вызывая loadImages() происходит краш, при этом не всегда.
Обновлялся с версии 6.4.0 и YandexMobileAdsInstream 0.24.0.

<img width="1430" alt="Screenshot 2024-04-09 at 17 54 24" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/42266896/5bffd06e-845b-4913-aa6f-876235869bb8">
<img width="1419" alt="Screenshot 2024-04-09 at 17 55 08" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/42266896/d7a7ffbe-7450-4aa6-b753-5171f8fea767">

**Comment by mobile-ads-github** [comment]
Добрый день. У нас проблема не воспроизводится в сэмпл приложение, можете поделиться полным стектрейсом, а так же кодом, где используете метод loadImages().

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3124. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3124 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
