### ISSUE TITLE
Content is not scalled properly

### ISSUE THREAD

**Issue by TopIvanAbramov** [yandexmobile/yandex-ads-sdk-ios#217]
As a content mode you use scaleAspectFit which works incorrectly in case aspect ratio of the view is slightly different from the banner image.

2,3982300885 vs 2,3907284768

Hence, banner has a thin white stripes on the left & right

Suggestion: use scaleAspectFill as a content mode
![photo_2024-05-13 11 29 02](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/42469397/d7f4e48a-5bde-4417-9ffb-a6e8f7332340)

**Comment by mobile-ads-github** [comment]
Hi! We check on our side. We will try to consider it in the next release.

**Comment by mobile-ads-github** [comment]
Hi! We can't change the content mode in the SDK. We suggest using rounded aspect ratio values.
