### ISSUE TITLE
Неверная высота feedback view

### ISSUE THREAD

**Issue by ReshetovE** [yandexmobile/yandex-ads-sdk-ios#218]
Высота feedback view не подстраивается под контент.
Чаще всего очень много пустого места на открытом дровере
<img width="469" alt="Screenshot 2024-05-17 at 17 35 25" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/14102700/c4002359-308e-482e-b09c-76873102a5bf">

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3253. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3253 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте, это ожидаемое поведение в SDK.
