### ISSUE TITLE
Crash on version 7.0.1

### ISSUE THREAD

**Issue by dovanvu1792** [yandexmobile/yandex-ads-sdk-ios#219]
This is crash log on Firebase.
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0xde88 object_getClass + 48
1  Foundation                     0x1bfbc _NSKeyValueObservationInfoGetObservances + 268
2  Foundation                     0x1b47c NSKeyValueWillChangeWithPerThreadPendingNotifications + 236
3  AVFCore                        0x4a058 __67-[AVPlayer _createAndConfigureFigPlayerWithType:completionHandler:]_block_invoke_2 + 164
4  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
6  libdispatch.dylib              0x125a4 _dispatch_main_queue_drain + 988
7  libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
8  CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0xea84 class_getMethodImplementation + 84
1  Foundation                     0x1c31c _NSKVONotifyingOriginalClassForIsa + 32
2  Foundation                     0x1bfcc _NSKeyValueObservationInfoGetObservances + 284
3  Foundation                     0x1b47c NSKeyValueWillChangeWithPerThreadPendingNotifications + 236
4  AVFCore                        0x4a058 __67-[AVPlayer _createAndConfigureFigPlayerWithType:completionHandler:]_block_invoke_2 + 164
5  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
7  libdispatch.dylib              0x125a4 _dispatch_main_queue_drain + 988
8  libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3254. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3254 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Hi! We don't see our classes in this stack trace. Can you provide a full stack trace where you can see that the problem is on the SDK side?

**Comment by dovanvu1792** [comment]
There is no reference Yandex class, but version 5.2.1 did not see this crash log on Firebase

**Comment by dovanvu1792** [comment]
This issue was fixed on version 7.0.2
