### ISSUE TITLE
Не останавливаются запросы геолокации после удаления рекламного баннера

### ISSUE THREAD

**Issue by maxim4to** [yandexmobile/yandex-ads-sdk-ios#22]
Предусловие: 
разрешен доступ к геолокации при использовании приложения

Тесткейс:
1. Отобразить экран с рекламой, появляется индикатор запросов геолокации в статус баре.
2. Скрыть экран(удалить инстансы `NativeContentAdView,` `NativeAppInstallAdView`, `YMANativeAdLoader`), индикатор не исчезает.

Результат: геолокация запрашивается постоянно при работе приложения, даже если реклама уже не показывается.

Если засвизлить методы `startUpdatingLocation` и `stopUpdatingLocation` у `CLLocationManger`-а, то заметно, что `stopUpdatingLocation` не вызывается после деинита рекламы. В MemoryGraph видно, что существуют два инстанса `CLLocationManger`, но активно слушает геопозицию инстанс со следующим графом:

![screen shot 2018-04-25 at 12 29 53](https://user-images.githubusercontent.com/3517394/39237592-a1b0c180-4884-11e8-9422-e61ebe0a2ee2.png)

Также, метод `startUpdatingLocation` не является энергоэфеективным и, если на экране будет много рекламы(или она будет на всех экранах), то мы получим очень много запросов геолокации(это бесит пользователей). Возможно стоит перейти на метод `startMonitoringSignificantLocationChanges` или обновлять геолокацию по таймауту.

**Comment by kried** [comment]
Здравствуйте.

Спасибо за ваше сообщение, мы рассмотрим возможность обновить трекинг геолокации в следующих релизах.

В данный момент вы можете отключить трекинг геолокации вызовом 
```[YMAMobileAds  setLocationTrackingEnabled:NO]```
https://tech.yandex.ru/mobile-ads/doc/dg/ios/ref/YMAMobileAds-docpage/#method_detail__method_setLocationTrackingEnabled__BOOL

Геолокацию в рекламный запрос при выключенном трекинге можно передать в свойстве ```location``` объекта класса```YMAAdRequest```.
https://tech.yandex.ru/mobile-ads/doc/dg/ios/ref/YMAAdRequest-docpage/

**Comment by maxim4to** [comment]
@kried  Хорошо, тогда такой вопрос - отключение геолокации и отправка своей CLLocation может как то повлиять на выплаты за рекламу?

**Comment by kried** [comment]
Есди вы будете передавать валидную геолокацию в объект класса ```YMAAdRequest```, то выплаты за рекламу не должны упасть. Если вы просто отключите трекинг локации и не будете устанавливать дополнительно локацию в ```YMAAdRequest```, то реклама будет хуже таргетироваться, и возможны изменения в подборе рекламы и в выплатах.

**Comment by mobile-ads-github** [comment]
Проблема исправлена для SDK версий 3.x.x и 4.x.x
