### ISSUE TITLE
Please specify os version

### ISSUE THREAD

**Issue by alobanov11** [yandexmobile/yandex-ads-sdk-ios#220]
When I upload my application to the app store an error occurs. I connected your library via spm package

![Снимок экрана 2024-05-22 в 15 30 28](https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/5923243/7015ee4b-d354-4290-b4e4-fb88b457accb)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3262. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3262 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
