### ISSUE TITLE
Did not catch error when show OpenAds

### ISSUE THREAD

**Issue by dovanvu1792** [yandexmobile/yandex-ads-sdk-ios#223]
Step 1: Open Dialog
Step 2: Enter background 
Step 3: Enter foreground, at this step, can not present OpenAds because there is other view controller already presenting. But can not received any error from Yandex Open ads delegate. 
This function do not enter: ` _func appOpenAd(_ appOpenAd: AppOpenAd, didFailToShowWithError error: Error) {}_`
Test on version 7.0.1, 7.02, 7.1.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3327. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3327 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by dovanvu1792** [comment]
Be careful check interstitial ads too.

**Comment by dovanvu1792** [comment]
I checked new version 7.1.1, it's doesn't fix this issue.
