### ISSUE TITLE
Ошибка: Ad request completed successfully, but there are no ads available

### ISSUE THREAD

**Issue by TimKaldybek** [yandexmobile/yandex-ads-sdk-ios#224]
Добрый день. 
В методе didFailLoadingWithError, получаем ошибку Ad request completed successfully, but there are no ads available с кодом ошибки 3. 
В чем может быть причина и как добиться чтобы такой ошибки не было?

Метод: - (void)nativeAdLoader:(YMANativeAdLoader * _Nonnull)loader didFailLoadingWithError:(NSError * _Nonnull)error

Вот версии которые используем:

pod 'MyTargetYandexMobileAdsAdapters', '5.21.1.0'
pod 'YandexMobileAds', '7.0.0'

Вижу что в 22 году обращались с подобным вопросом, но проблема возобновилась:
https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/106

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3330. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3330 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за сообщение о проблеме.
Пришлите пожалуйста id рекламного блока и id приложения на почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru) для того, чтобы мы могли подробнее разобраться в причинах возникновения проблемы.

**Comment by TimKaldybek** [comment]
*Тема: Проблемы с производительностью приложения при использовании нативной
рекламы Яндекс*

Добрый день!

Также хотелось бы уточнить, возможно, вы сталкивались с подобными жалобами
или проблемами.

У меня в приложении есть бесконечный список, и на каждом четвертом элементе
показывается нативная реклама Яндекс.

При длительном скролле (примерно 3-4 минуты) телефон начинает сильно
нагреваться.Телефон не на зарядке, все приложения были закрыты, активно
только мое приложение, и свободной памяти более 400 ГБ.

Что было замечено:

   - Память бесконечно растет, заполняясь элементами типа malloc blocks
   (см. прикрепленные фото malloc1 и memory).
   - Приложение просто находится на экране, и я никак с ним не
   взаимодействую.
   - Пример: я проскролил список в течение 2 минут и оставил телефон.
   Спустя время память (Memory Use) в Xcode увеличилась до 2 ГБ.
   - Если отключить загрузку нативной рекламы и повторить действия, память
   не растет и нет зависаний.


*Прошу вашего совета по поводу того, как справляться с таким поведением
приложения.*

Может что-то делаю не так.

Я проверил приложение (без показа нативной рекламы) на утечки памяти, и их
не было обнаружено.

Также уточню, что для подгрузки рекламы использую отдельный класс, в
котором на показ каждой рекламы создается класс *Example*.

Заранее благодарю за помощь. Надеюсь, у вас будет возможность ответить.

*Пример кода загрузки рекламы:*

*final* *class* Example: NSObject {

    *private* *var* adLoader: NativeAdLoader?

    *private* *var* loadedAd: NativeAd?



    *private* *let* advertIdentifier: String



    *init*(advertIdentifier: String) {

        *self*.advertIdentifier = advertIdentifier



        *super*.init()



        loadAd()

    }



    *private* *func* loadAd() {

        adLoader = NativeAdLoader()

        adLoader?.delegate = *self*

        *let* requestConfiguration =
MutableNativeAdRequestConfiguration(adUnitID: advertIdentifier)

        adLoader?.loadAd(with: requestConfiguration)

    }

}


*extension* Example: NativeAdLoaderDelegate {

    *func* nativeAdLoader(_ loader: YandexMobileAds.NativeAdLoader, didLoad
ad: *any* YandexMobileAds.NativeAd) {

        //handle success...

    }



    *func* nativeAdLoader(_ loader: YandexMobileAds.NativeAdLoader,
didFailLoadingWithError error: *any* Error) {

        //handle error...

    }

}



ср, 26 июн. 2024 г. в 17:49, mobile-ads-github ***@***.***>:
