### ISSUE TITLE
JSONSerialization.jsonObject сrash exc_bad_access  

### ISSUE THREAD

**Issue by kosta-khetagurov** [yandexmobile/yandex-ads-sdk-ios#225]
Добрый день!

Окружение:
Xcode 15.4
Cocoapods 1.15.2
YandexMobileAds 7.10

После установки YandexMobileAds 7.10, запускаю приложение и ловлю крэши с exc_bad_access при вызове JSONSerialization.jsonObject(with:options:) в одном из подов. 
Воспроизводится стабильно и только с установленной YandexMobileAds. Есть вероятность, что это связано с тем, что framework экспортирует дублирующие символы (NSJSONReadingOptions) и рантайм не может определить какой конструктор использовать.
При этом реклама и сдк работают.

Thread 17 Crashed::  Dispatch queue: MyClassQueue
0   libswiftCore.dylib            	       0x19295e298 swift::SubstGenericParametersFromMetadata::SubstGenericParametersFromMetadata(swift::TargetMetadata<swift::InProcess> const*) + 24
1   libswiftCore.dylib            	       0x1929665b4 swift_getAssociatedTypeWitnessSlowImpl(swift::MetadataRequest, swift::TargetWitnessTable<swift::InProcess>*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolRequirement<swift::InProcess> const*, swift::TargetProtocolRequirement<swift::InProcess> const*) + 252
2   libswiftCore.dylib            	       0x192964d38 swift_getAssociatedTypeWitness + 52
3   libswiftCore.dylib            	       0x1927adad4 OptionSet<>.init() + 76
4   OK                            	       0x102d73074 protocol witness for SetAlgebra.init() in conformance CACornerMask + 52
5   OK                            	       0x103081348 protocol witness for SetAlgebra.init() in conformance VAButtonStyle + 12
6   OK                            	       0x10321e71c protocol witness for SetAlgebra.init() in conformance NSJSONReadingOptions + 12
7   libswiftCore.dylib            	       0x1927c7ff8 SetAlgebra.init<A>(_:) + 272
8   OK                            	       0x103474fd0 protocol witness for SetAlgebra.init<A>(_:) in conformance NSJSONReadingOptions + 44
9   libswiftCore.dylib            	       0x1927c8314 SetAlgebra<>.init(arrayLiteral:) + 132
10  OK                            	       0x105347004 closure #1 in MyClass.myfunc(param1:param2:param3:) + 3432
11  OK                            	       0x102b11478 thunk for @escaping @callee_guaranteed @Sendable () -> () + 28
12  libdispatch.dylib             	       0x18016a4f4 _dispatch_call_block_and_release + 24
13  libdispatch.dylib             	       0x18016bd3c _dispatch_client_callout + 16
14  libdispatch.dylib             	       0x180173e3c _dispatch_lane_serial_drain + 960
15  libdispatch.dylib             	       0x1801749b4 _dispatch_lane_invoke + 388
16  libdispatch.dylib             	       0x18017fd40 _dispatch_root_queue_drain_deferred_wlh + 276
17  libdispatch.dylib             	       0x18017f38c _dispatch_workloop_worker_thread + 448
18  libsystem_pthread.dylib       	       0x11682b814 _pthread_wqthread + 284
19  libsystem_pthread.dylib       	       0x11682a5d4 start_wqthread + 8

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3377. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3377 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за сообщение о проблеме.
Пришлите, пожалуйста, Podfile и Podfile.lock на почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru) для того, чтобы мы могли подробнее разобраться в причинах возникновения проблемы.

**Comment by mobile-ads-github** [comment]
Добрый день, воспроизводится ли у вас данная проблема в новых версиях SDK?
