### ISSUE TITLE
У наследника YMANativeAdView объект id<YMANativeAd> ad равен nil

### ISSUE THREAD

**Issue by blashkin** [yandexmobile/yandex-ads-sdk-ios#226]
После вызова метода bindAd(toSliderView:) у наследника YMANativeAdView свойство ad равно nil.
Пример:
```
try ad.bindAd(toSliderView: sliderView)
sliderView.ad // nil
```
Когда как после вызова метода bind(with:) объект живой и можно сразу к нему обратиться.
Пример:
```
try ad.bindAd(with: view)
view.ad // живой объект
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3395. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3395 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за обращение, в следующем релизе проблема будет решена.
