### ISSUE TITLE
Swift Ui

### ISSUE THREAD

**Issue by etoevelina** [yandexmobile/yandex-ads-sdk-ios#228]
Здравствуйте! А как это со SwiftUI испоьзовать? Предоставьте пожалуйста нормальный код для подключения межстраничной рекламы для приложения на SwiftUI🙏

**Comment by mobile-ads-github** [comment]
Здравствуйте, подскажите, пожалуйста, с чем именно возникает проблема? Начиная с версии sdk 7.2.0 есть возможность передать nil при вызове метода show(from:) для InterstitialAd, RewardedAd, AppOpenAd.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3409. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3409 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
