### ISSUE TITLE
Интеграция как статической библиотеки через CocoaPods

### ISSUE THREAD

**Issue by OneSman7** [yandexmobile/yandex-ads-sdk-ios#23]
CocoaPods добавили возможность собирать поды на Swift не как фреймворки, а как статические библиотеки, что уменьшает время запуска приложения.
Для этого надо убрать use_frameworks! из podfile.

Но после этого возникают ошибки импорта библиотеки как модуля (`import YandexMobileAds` в swift файле). `Could not build Objective-C module`.
Причина - набор ошибок в umbrella заголовке типа` Include of non-modular header inside framework module`.
На мой взгляд, возможная причина - наличие в файлах `YandexMobileAds.h,` `YandexMobileNativeAds.h`, `YandexMobileVASTAds.h` импортов, которые уже добавлены ниже в в umbrella заголовке. К тому же импорты там идут через <>.

Workaround пока - импортировать под через bridging header главного проекта:

```
#pragma mark - YandexMobileAds

#import <YandexMobileAds/YandexMobileAds.h>
#import <YandexMobileAds/YandexMobileNativeAds.h>
```
 
Однако, хотелось бы использовать swift импорт как у остальных библиотек.

**Comment by kanstantsin** [comment]
Добрый день. Спасибо за детальный отчет. В ближайшее время постараемся исправить проблему.

**Comment by kried** [comment]
Добрый день

Попробуйте использовать версию 2.9.0, в ней проблема должна быть исправлена.

**Comment by OneSman7** [comment]
Да, спасибо! Компилирует, закрываю баг.
