### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by EvelinaAlexey** [yandexmobile/yandex-ads-sdk-ios#232]
Attempt to present <MobileAdsCore.FullscreenNativeViewController: 0x10a04de00> on <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x109813a00> (from <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x109813a00>) which is already presenting <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x10a00e200>.
Подскажите с чем связана ошибка?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3445. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3445 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Подскажите пожалуйста:
- какую версию SDK вы используете?
- не могли бы вы прислать сниппет кода с интеграцией?

**Comment by mobile-ads-github** [comment]
Добрый день, подскажите, воспроизводится ли у вас данная проблема сейчас?
