### ISSUE TITLE
Podfile source

### ISSUE THREAD

**Issue by Algashev** [yandexmobile/yandex-ads-sdk-ios#233]
У вас в тестовом проекте в `Podfile` указано в качестве источника:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
```
Однако Cocoapods [рекомендует использовать CDN](https://blog.cocoapods.org/CocoaPods-1.8.0-beta/):

``` ruby
source 'https://cdn.cocoapods.org/'
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3460. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3460 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Добавим в одном из следующих релизов
