### ISSUE TITLE
Утечки памяти YandexMobileAdsInstream версия 0.30.0

### ISSUE THREAD

**Issue by Algashev** [yandexmobile/yandex-ads-sdk-ios#234]
## Шаги для воспроизведения:

1. Клонировать текущий проект с `GithHub` версия **YandexMobileAds** `7.1.1`.
2. Установить `Podfile`.
3. Запустить проект в `Xcode`.
4. В приложении перейти: `Yandex Ads` > `Instream` > `Single Instream`.
5. На экране **Single Instream** поочередно нажимаем кнопки: `Load` > `Prepare ad` > `Present ad`.
6. После просмотра рекламы выходим на предыдущий экран (_кнопка `Back`_).
7. Нажимаем в `Xcode` кнопку `Debug Memory Graph`:
<img width="279" alt="Снимок экрана 2024-07-15 в 09 51 42" src="https://github.com/user-attachments/assets/70c1106a-f9f1-4ff2-932c-837a82768acd">

8. Наблюдаем утечки:
<img width="410" alt="Снимок экрана 2024-07-15 в 09 41 44" src="https://github.com/user-attachments/assets/590636c5-c2be-4176-b39b-3b82b97789ea">

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3459. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3459 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Мы устраним проблему в следующем релизе
