### ISSUE TITLE
CocoaPods Error

### ISSUE THREAD

**Issue by dovanvu1792** [yandexmobile/yandex-ads-sdk-ios#239]
Yandex version: 7.2.0, 7.3.0
Pod version: 1.15.2
MacOS: 14.4.1
Xcode: 15.0

> ld: Undefined symbols:
>   __swift_FORCE_LOAD_$_swiftXPC, referenced from:
>       __swift_FORCE_LOAD_$_swiftXPC_$_YandexMobileAds in YandexMobileAds[9] (AdInfo.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MobileAdsCore in YandexMobileAds[95] (MACHTMLControlFactory.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MACBase in YandexMobileAds[820] (MACOptionalDecodable.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MACBaseUI in YandexMobileAds[924] (MACActionsViewController.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MACDependenciesUmbrella in YandexMobileAds[986] (MACCompositeReportParametersProvider.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MACPlatformDescription in YandexMobileAds[992] (MACLocaleProvider.o)
>       __swift_FORCE_LOAD_$_swiftXPC_$_MACNetworking in YandexMobileAds[1003] (MACAdsHTTPResponseStatusCodeValidator.o)
>       ...
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3537. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3537 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by MaksimUstimenko** [comment]
Проблема сохраняется в YandexMobileAds с версией 7.3.2
`ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_YandexMobileAds in YandexMobileAds[9](AdInfo.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MobileAdsCore in YandexMobileAds[96](MACHTMLControlFactory.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACBase in YandexMobileAds[829](MACBundleProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACBaseUI in YandexMobileAds[931](MACActionsViewController.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACDependenciesUmbrella in YandexMobileAds[993](MACCompositeReportParametersProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACPlatformDescription in YandexMobileAds[999](MACLocaleProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACNetworking in YandexMobileAds[1010](MACAdsHTTPResponseStatusCodeValidator.o)
      ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by mobile-ads-github** [comment]
Добрый день, попробуйте собрать проект используя последнюю версию Xcode

**Comment by mobile-ads-github** [comment]
@MaksimUstimenko здравствуйте, помог ли переход на новую версию XCode в решении проблемы?
