### ISSUE TITLE
Отображение рекламы в ячейки таблицы

### ISSUE THREAD

**Issue by sskurzhanskiy** [yandexmobile/yandex-ads-sdk-ios#24]
При попытке отображения рекламы как ячейки в таблице, в лог падает предупреждение:
<Warning>: Impression could not be tracked. Will attempt to track impression later. Error: Ad view is not visible for required percent
Я так понимаю что показ засчитан не будет ?

**Comment by kanstantsin** [comment]
Добрый день!

Как говорится в сообщении, позже будет выполнена еще одна проверка, и если объявление показано на необходимый процент, то показ засчитан будет.
Это можно будет понять по сообщению "Ad binding successful" в логах. Также можно воспользоваться индикатором интеграции: https://tech.yandex.ru/mobile-ads/doc/dg/ios/quick-start/debug-mode-docpage/
Если нет красной рамки при включенном индикаторе, значит все хорошо, и показ засчитается.

**Comment by sskurzhanskiy** [comment]
Добрый день, спасибо за ответ. 
Подскажите, в течении какого времени надо отображать баннер на экране что бы показ засчитался. При условии что все элементы видны, конечно же

**Comment by kanstantsin** [comment]
Необходимое время для показа может меняться в зависимости от различных факторов, на какое-то определенное значение не стоит рассчитывать. Сейчас в большинстве случаев это 2 секунды, но опять же хочу обратить внимание, что в любой момент это может измениться.
В кеш объявления складывать можно. Но мне пока не очень понятно, для каких целей вы хотите показывать незасчитанные объявления заново. Если расскажете причины, то, возможно, мы сможем подсказать, насколько это необходимо или дать какие-либо рекомендации.
Максимальное количество времени между получением и показом не определено. Но чем меньше времени пройдет между ответом и показом, тем актуальнее будет объявление для пользователя.

**Comment by sskurzhanskiy** [comment]
Причина складывания в кеш в следующем. Реклама показывается в таблице, после прихода контента рекламы, ее надо отобразить, т.е вставить в новую ячейку в таблицу, соответственно остальные ячейки в таблице разъезжаются, что плохо для пользователя. Для этого мы используем небольшой кеш с рекламой, откуда берем уже скаченную рекламу, и до отрисовки таблицы у нас есть все данные для отображения . Для уменьшения числа запросов рекламы, мы закладываемся на то что если реклама отображается меньше 2-х секунд, возвращаем ее в кеш, для последующего повтора, но как я понял из Вашего ответа, это не правильно.

**Comment by kanstantsin** [comment]
Описанное Вами поведение по кешированию рекламы для отображения в списках вполне нормальное и ожидаемое. Но логика по возврату объявления в кеш скорее избыточна, хотя нельзя назвать ее неправильной. Если от нее избавиться, то насколько я могу судить, эффективность рекламы хуже не станет. Из плюсов вижу экономию сетевых запросов, но не думаю, что она будет очень значительна. Из минусов - усложнение логики приложения и неоднозначный UX, в котором пользователь чаще будет видеть дублирующиеся объявления.
В итоге, я бы порекомендовал оставить логику кеширования, но без повторения показа уже отображенных на небольшое время объявлений. Но повторюсь, решение не является неправильным, его эффективность нужно оценивать с точки зрения важных для Вас метрик.

**Comment by sskurzhanskiy** [comment]
Спасибо за Ваши ответы, Вы нам очень помогли
