### ISSUE TITLE
SPM: mixed language source files

### ISSUE THREAD

**Issue by timokhin** [yandexmobile/yandex-ads-sdk-ios#240]
Привет. На версиях 7.2.0+ не удается обновить зависимости SPM:

```bash
xcodebuild: error: Could not resolve package dependencies:
  target at '/path/to/DerivedData/SourcePackages/checkouts/yandex-ads-sdk-ios/Sources/YandexMobileAdsTarget' contains mixed language source files; feature not supported
```
В директории содержится файл `dummy.swift`. Если удалить его руками и перезапустить xcodebuild, ошибка пропадает. Файл был добавлен в релизе 7.2.0, судя по всему.

XCode 15.4 15F31d

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за то, что указали на проблему. Исправим в следующем релизе.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3557. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3557 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
L
