### ISSUE TITLE
 Showing Recent Issues Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Saykudan** [yandexmobile/yandex-ads-sdk-ios#244]
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_YandexMobileAds in YandexMobileAds[x86_64][9](AdInfo.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MobileAdsCore in YandexMobileAds[x86_64][96](MACHTMLControlFactory.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACBase in YandexMobileAds[x86_64][829](MACBundleProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACBaseUI in YandexMobileAds[x86_64][931](MACActionsViewController.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACDependenciesUmbrella in YandexMobileAds[x86_64][993](MACCompositeReportParametersProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACPlatformDescription in YandexMobileAds[x86_64][999](MACLocaleProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_MACNetworking in YandexMobileAds[x86_64][1010](MACAdsHTTPResponseStatusCodeValidator.o)
      ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please how to fix this i've spent the whole day and nothing :(

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3642. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3642 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by Saykudan** [comment]
Any updates on this please :(

**Comment by mobile-ads-github** [comment]
Hello, could you please provide the following details:
1. The version of the SDK you are using.
2. The version of Xcode you are running.
