### ISSUE TITLE
Нельзя прочитать информацию о рекламе из-за автоматического закрытия шторки 

### ISSUE THREAD

**Issue by olganma** [yandexmobile/yandex-ads-sdk-ios#246]
**Шаги воспроизведения:**
1. Тап на «...» (три точки) на рекламном объявлении
2. В шторке «Рекламное объявление» тап на любой пункт со стрелкой (внешней ссылкой), например - «О рекламодателе»

**Ожидаемый результат:**
Шторка «Рекламное объявление» автоматически не закрывается. Информацию о рекламе в открывшемся внутреннем браузере можно внимательно прочитать. 

**Фактический результат:**
Шторка «Рекламное объявление» через 5 секунд автоматически закрывается, нет возможности нормально ознакомиться с информацией по внешней ссылке.

Пример (из приложения Авито)
https://github.com/user-attachments/assets/bb07d853-d4e7-4cb8-81a5-2981ed601293

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3685. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3685 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за сообщение о проблеме. Решим её в ближайших релизах.
