### ISSUE TITLE
Срабатывает тач при скролле баннера

### ISSUE THREAD

**Issue by olganma** [yandexmobile/yandex-ads-sdk-ios#247]
**Описание:**
При скролле страницы, на которой присутствует баннер, преимущественно ведущий в AppStore (ВкусВилл, Hoff), срабатывает клик, хотя непосредственного тача по баннеру не было. 

Пример из приложения Clatch https://github.com/user-attachments/assets/6c95c694-fa21-4af0-8a73-f8965bc0a1dd

**Ожидаемый результат:**
При скролле ложное срабатывание не происходит. Клик происходит только при непосредственном таче на баннер.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3728. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3728 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Спасибо, что указали на проблему, исправим в одном из следующих релизов.

**Comment by mobile-ads-github** [comment]
Добрый день @olganma! Воспроизводится ли у вас баг на последней версии SDK? Если да. то пришлите нам на почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru) свой adUnitID (вида R-M-XXXXX-YY).
