### ISSUE TITLE
Краш при создании YMANativeMediaView

### ISSUE THREAD

**Issue by ValentineVV** [yandexmobile/yandex-ads-sdk-ios#249]
При создании YMANativeMediaView часто появляется краш
<img width="534" alt="Screenshot 2024-09-11 at 11 11 04" src="https://github.com/user-attachments/assets/09614f61-32bd-4241-9b46-fc2c1faf346a">

Версии подов, на которых точно воспроизводится: 7.1.1 и 7.3.2

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3751. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3751 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, можете, пожалуйста, предоставить код, где вы создаете YMANativeMediaView?

**Comment by ValentineVV** [comment]
Вот так создаем, крашится в первой же строчке.
let view = YMANativeMediaView()
        view.contentMode = .scaleAspectFill
        view.backgroundColor = .veryLightBlue
        view.layer.borderWidth = 1
        view.layer.borderColor = UIColor.veryLightBlue.cgColor
        return view

**Comment by mobile-ads-github** [comment]
Добрый день, опубликуем фикс в следующем релизе
