### ISSUE TITLE
'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 480]'

### ISSUE THREAD

**Issue by samsonow19** [yandexmobile/yandex-ads-sdk-ios#25]
Краш на Iphone5 (se) IOS 12
'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 480]'
 pod 'YandexMobileMetrica', '~> 3.2.0'
 pod 'YandexMobileAds', '~> 2.10.0'

**Comment by kried** [comment]
Здравствуйте, спасибо за репорт.
Предоставьте, пожалуйста, более полный стектрейс креша. Также нам будет полезным узнать сценарий, когда ошибка воспроизводится, если это известно. 
Какой тип рекламы вы используете у себя в проекте: баннер, полноэкранная или нативная реклама.

**Comment by samsonow19** [comment]
-- | -- | -- | -- | --
14 | \| | 10:29:49:450 (UTC) | \| | YMAInterstitialRootViewController viewDidLoad
15 | \| | 10:29:49:453 (UTC) | \| | YMAInterstitialRootViewController viewWillAppear
16 | \| | 10:29:49:468 (UTC) | \| | YMAInterstitialAdViewController viewDidLoad
17 | \| | 10:29:49:471 (UTC) | \| | YMAInterstitialAdViewController viewWillAppear
(YMAInterstitialController)
interstitial.presentInterstitial(from: view)
Вам нужны параметры которые я передаю в YMAAdRequest? 

[com.spartak_issue_406_crash_7c2651659a764ea794dafded61eca548_DNE_0_v2.txt](https://github.com/yandexmobile/yandex-ads-sdk-ios/files/2460028/com.app_issue_406_crash_7c2651659a764ea794dafded61eca548_DNE_0_v2.txt)

**Comment by kried** [comment]
Подскажите, пожалуйста, как часто воcпроизводится креш? Воспроизводится ли он только на каком-то одном указанном девайсе или версии оси?
Подскажите еще, пожалуйста, как у вас получилось связать креш из crashlytics и указанный выше лог про показ интерстишла:

> 14 | | | 10:29:49:450 (UTC) | | | YMAInterstitialRootViewController viewDidLoad

Получалось ли у вас воспроизвести такой креш самому или только увидеть в отчете crashlytics?

**Comment by samsonow19** [comment]
На старой версии 100% воспроизводился, потом обновил библиотеку, баг стал плавающим. Возможно проблема в моей реализации, но так как не имею доступа к исходникам еще не проверил. Через свизлинг написал модуль который включается через конфинг и переопределяет viewDidLoad и вызывает его super(краш репорт был просто мало информативным) :)

**Comment by kried** [comment]
Подскажите, пожалуйста, версию библиотеки, на которой у вас воспроизводился стабильно баг.
И если у вас будет возможность, может вы сможете прислать какой-то маленький тестовый сампл, в котором креш повторяется?

**Comment by samsonow19** [comment]
Добрый день. Можно получить вашу почту? на нее пришлю ссылку на сампл.

**Comment by kried** [comment]
Здравствуйте

Пришлите, пожалуйста, ваш сампл на mail mobile-ads-github@yandex-team.ru

**Comment by kried** [comment]
Здравствуйте

На данный момент на вашем сампле у нас не получается воспроизвести баг. Может быть у вас есть дополнительные данные, которые помогут нам воспроизвести его?
Подскажите, пожалуйста, версию сдк, на которой у вас стабильно воспроизводился баг. 
Может быть, у вас есть логи запросов в сеть, записанные в сниффере, на которых воспроизводится креш? Например, записанная сессия в сниффере Charles.

**Comment by kried** [comment]
Спасибо за присланные самплы. Креш удалось воспроизвести. В одном из ближайших релизов он будет исправлен.

**Comment by kried** [comment]
Здравствуйте

Вышла версия библиотеки 2.11.1, в ней проблема должна быть исправлена.
