### ISSUE TITLE
Использование с maccatalyst 

### ISSUE THREAD

**Issue by NikKovIos** [yandexmobile/yandex-ads-sdk-ios#254]
Добрый день)

Пытаюсь запустить под maccatalyst (rosetta) и получаю такие ошибки:

```
framework 'YandexMobileAds' not found
linker command failed with exit code 1 (use -v to see invocation
```

Под iOS запускается. Подскажите пожалуйста куда копать чтобы можно было использовать на маках и ipad с apple silicon процессорах. Поидее хоть это и mobileads,  но эппл унифицировала архивацию так что должно работать.

<details><summary>Podfile:</summary>
platform :ios, '15.0'

inhibit_all_warnings!
use_frameworks!

abstract_target 'MunchkinAbstract' do
  pod 'Firebase/Messaging', '11.1.0' # тут есть core
  pod 'Firebase/Analytics', '11.1.0'
  pod 'YandexMobileAds', '7.5.1'
  pod 'AppMetricaAnalytics', '5.8.1'

  pod 'MMMarkdown', '0.5.5'
  pod 'SteviaLayout', '5.1.2'
  pod 'Colorful', "3.0.0"
  pod 'LGAlertView', "2.4.3"

  target 'Munchkinopedia'

end

post_install do |pi|
  pi.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
</details>

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3876. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3876 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, мы не поддерживаем maccatalyst
