### ISSUE TITLE
не вызывается метод делегата RewardedAdDelegate rewardedAdDidDismiss

### ISSUE THREAD

**Issue by astrokin** [yandexmobile/yandex-ads-sdk-ios#256]
последовательность вызовов методов делегата:
1) rewardedAdDidShow
2) didReward
3) нажимаю закрыть
4) экран исчезает
3) метод `rewardedAdDidDismiss` не вызывается

**Comment by mobile-ads-github** [comment]
Добрый день, какую версию SDK вы используете? Воспроизводится ли баг на версии 7.6.0?
