### ISSUE TITLE
Обращение к dyld3::MachOLoaded::findClosestSymbol каждые 10 секунд подвешивает систему.

### ISSUE THREAD

**Issue by blashkin** [yandexmobile/yandex-ads-sdk-ios#257]
Использовал профайлер на вашем примере YandexMobileAdsExampleSPM, чтобы исключить сторонние сдк в нашем проекте, как видно на скриншоте пики повторяются каждые 10 секунд. 
<img width="1450" alt="Снимок экрана 2024-10-03 в 18 41 06" src="https://github.com/user-attachments/assets/52fb0c1c-0f1b-4273-b21e-37c894ae6622">

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3910. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3910 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Это системный вызов, поэтому мы не можем точно сказать, есть ли проблема на нашей стороне. Изучим кейс.
