### ISSUE TITLE
SKOverlay remains on screen after interstitial ads

### ISSUE THREAD

**Issue by vladislav-h** [yandexmobile/yandex-ads-sdk-ios#258]
Users are reporting that sometimes a banner appears after interstitial ads. At the bottom is a blurred screenshot of the issue. It seems to me that this banner is SKOverlay that was added in SDK7 ( https://ads.yandex.com/sdk7 ). For some reason the SKOverlay remains on screen after the interstitial, it is impossible to close it and (in our app) it covers half of the keyboard. Is there a way to disable SKOverlay and what to do with this? Something is broken.

The first reports of the problem came when we were using SDK version 7.4.0. We then downgraded to SDK version 6.4.1 hoping that the ads with SKOverlay only exist in SDK7. But apparently such ads can also be shown with SDK version 6.4.1.

![image0](https://github.com/user-attachments/assets/bc194cea-8442-4f37-9d9e-5c10bbc9793c)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3912. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3912 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Good afternoon! We see your issue. We will fix it in upcoming versions.
