### ISSUE TITLE
"Banner returned by server is invalid" в VideoExample

### ISSUE THREAD

**Issue by tym2018** [yandexmobile/yandex-ads-sdk-ios#27]
Запускаем VideoExample.
В BlockViewController выпадаем в loaderDidFailLoadingVideoAdsWithError с ошибкой 

> VideoExample[20413:1070597] Failed loading. Error: Error Domain=com.yandex.mobile.YandexMobileAds Code=5 "Banner returned by server is invalid" UserInfo={NSLocalizedDescription=Banner returned by server is invalid}

Что-то где-то не так, или VideoExample не предполагает возврата реального YMAVASTAd объекта?

**Comment by kried** [comment]
Здравствуйте

VideoExample с дефолтными значениями не предполагает возврата реального YMAVASTAd. Для получения реальной рекламы нужно заменить значения ```partnerID```,  ```categoryID```, ```targetRef``` и ```pageRef``` на реальные значения. Для получения реальных значений вы можете связаться с вашим менеджером.

**Comment by kried** [comment]
Спасибо за предложение. Задача на создание демонстрационных блоков уже стоит. В скором времени мы обновим самплы, чтобы они работали именно с такими демонстрационными блоками.

**Comment by kried** [comment]
Здравствуйте

Мы добавили новый формат рекламы — VMAP/VAST. Пример его использования можно увидеть VASTExample. В этом примере используются демонстрационные блоки, с которыми приходит успешный ответ с рекламой.

Для загрузки VAST рекламы мы рекомендуем использовать именно новое апи.
