### ISSUE TITLE
Размер YMAAdView 

### ISSUE THREAD

**Issue by samsonow19** [yandexmobile/yandex-ads-sdk-ios#28]
Возможно программно поменять размер(подогнать под размер ячейки) YMAAdView?

**Comment by samsonow19** [comment]
Когда я увеличиваю YMAAdView. Реклама отображается не на весь размер YMAAdView. Даже если указываю различный YMAAdSize.

**Comment by kried** [comment]
Да, при увеличении размеров YMAAdView размер контента самой рекламы не изменяется. Вы можете воспользоваться одним из вариантов flex size. В этом случае если реальные размеры баннера меньше размеров YMAAdView, то под баннером будет отрисована адаптивная подложка вместо прозрачности.
https://tech.yandex.ru/mobile-ads/doc/dg/ios/ref/YMAAdSize-docpage/

**Comment by samsonow19** [comment]
Задача в том, что бы на всех устройствах, реклама сочеталась с нашим основным контентом. Так как достичь такого результата? На данный момент мы используем банер 300x250 и по краям у нас отступы. Необходимо без адаптивной подложки.

**Comment by kried** [comment]
Избавится от отступов как раз и помогает адаптивная подложка, которая дополняет вью основным цветом баннера. Растянуть именно содержимое рекламы нет возможности.
<details><summary>Пример отображения</summary>
<img width="479" alt="sample" src="https://user-images.githubusercontent.com/3630656/49295672-6120aa00-f4c7-11e8-8766-a9cce32bfc17.png">
</details>
