### ISSUE TITLE
onShow callback

### ISSUE THREAD

**Issue by aserrr** [yandexmobile/yandex-ads-sdk-ios#29]
Добавьте, пожалуйста, коллбэк onShow() для YMAAdViewDelegate и YMANativeAdDelegate
Он нужен нам для медиации, чтобы вызвать соответствующий наш коллбэк в момент начала показа рекламы.

**Comment by satsakul** [comment]
Добрый день.
Не могли бы Вы уточнить несколько вопросов:
1. Для какой медиации?
2. В нативной рекламе Вы сами определяете когда начинать показ рекламного объявления.
3. Для какого приложения? Можете написать мне на почту: satsakul@yandex-team.ru

**Comment by aserrr** [comment]
Ок. Спасибо )
