### ISSUE TITLE
Could not cast value of type 'YMAInterstitialOrientationLocker' exception

### ISSUE THREAD

**Issue by MrAlt** [yandexmobile/yandex-ads-sdk-ios#3]
Sometimes I catch exception "Could not cast value of type 'YMAInterstitialOrientationLocker' (0x10136d580) to 'KrClient.AppDelegate' (0x1013597e0)." on this line of code: 

`let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate`

**Comment by kanstantsin** [comment]
That's most likely a bug.
It will be fixed, but not sure if it's going to be fixed in the nearest future. The only thing I can suggest right now is to adapt the application code to handle cases when ```UIApplication.sharedApplication().delegate``` class is not ```AppDelegate```

**Comment by kanstantsin** [comment]
Fixed in 2.8.0
