### ISSUE TITLE
Target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by HiveHicks** [yandexmobile/yandex-ads-sdk-ios#4]
Пытаюсь создать под (назовем его `Foo`), который должен зависеть от YandexMobileAds. В podspec указываю зависимость:

`s.dependency 'YandexMobileAds'`

Затем подключаю под к приложению:

`pod 'Foo', :path => '../LocalPods/Foo'`

При попытке сделать `pod install` возникает ошибка:

`[!] The 'Pods-FooDemo' target has transitive dependencies that include static binaries: (<path-to-yandex>/YandexMobileAds/SDK/libYandexMobileAds.a)`

Пытался обернуть либу в динамический фреймворк, как описано тут http://mrdekk.ru/2016/04/30/cocoapods-static-transitive-binary-dependencies/, но, видимо, делаю что-то не так. `pod install` проходит, но сам под `Foo` не билдится, жалуясь на то, что `No such module YandexMobileAds`

**Comment by kanstantsin** [comment]
В ближайших планах есть поддержка дистрибуции в качестве динамического фреймворка, мы работаем над этим.

**Comment by HiveHicks** [comment]
В качестве временного решения я вручную сбилдил динамический фрэймворк `YandexMobileAds` и подключил его как локальный под. Podspec пода:

```
Pod::Spec.new do |s|
  s.name = "YandexMobileAds"
  s.version = "2.5.0"
  s.summary = "The Yandex Mobile Ads SDK provides mobile interfaces for Yandex Advertising Network" 

  s.homepage = "https://tech.yandex.ru/mobile-ads/"
  s.license = { :type => 'PROPRIETARY', :file => 'LICENSE.txt' }
  s.authors = { "Andrey Shender" => "ashender@yandex-team.ru", "Kanstantsin Charnukha" => "xardas@yandex-team.ru" }
  s.platform = :ios, '6.0'
  s.source = { :git => "https://github.com/yandexmobile/yandex-ads-sdk-ios.git", :tag => s.version.to_s}

  s.ios.vendored_frameworks = 'YandexMobileAds.framework'

  s.libraries = 'xml2'

  s.dependency 'YandexMobileMetrica', '>= 2.5.1', '< 3.0.0'
  s.frameworks = 'UIKit', 'Foundation', 'CoreTelephony', 'CoreLocation', 'CoreGraphics', 'CoreTelephony', 'AdSupport'
  s.weak_frameworks = 'SafariServices'

  s.requires_arc = true
end
```

Чтобы компилятор не ругался на импорты, так же пришлось добавить в podfile основного проекта пост-инсталл хук:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "MyPodThatDependsOnYandexMobileAds"
            target.build_configurations.each do |config|
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '$(inherited) "${PROJECT_DIR}/../../YandexMobileAds"'
            end
        end
    end
end
```

`pod install` и компиляция проходят успешно, однако при запуске приложения выдается рантайм ошибка о том, что не найдет фреймворк `YandexMobileMetrica`.

```
dyld: Library not loaded: @rpath/YandexMobileMetrica.framework/YandexMobileMetrica
  Referenced from: /Users/user/Library/Developer/CoreSimulator/Devices/3427651F-8BAB-4D05-98C4-A605DEE264E5/data/Containers/Bundle/Application/D6EB8CE9-4D4A-44AD-8E98-0C7B1F0CA3D6/MyApp.app/Frameworks/YandexMobileAds.framework/YandexMobileAds
  Reason: image not found
```

Если просмотреть содержимое package приложения, то его там действительно нет.

При этом если на данном этапе добавить `YandexMobileMetrica` как embedded framework в основное приложение, в рантайме возникает новая ошибка:

```
objc[69366]: Class PodYandexMobileMetrica_PodsDummy_YXStartupParameters is implemented in both /Users/user/Library/Developer/CoreSimulator/Devices/3427651F-8BAB-4D05-98C4-A605DEE264E5/data/Containers/Bundle/Application/32F9AAB4-7ECF-4FAA-8357-0CF5B0810354/MyApp.app/Frameworks/YandexMobileMetrica.framework/YandexMobileMetrica (0x1221b49b0) and /Users/user/Library/Developer/CoreSimulator/Devices/3427651F-8BAB-4D05-98C4-A605DEE264E5/data/Containers/Bundle/Application/32F9AAB4-7ECF-4FAA-8357-0CF5B0810354/MyApp.app/MyApp (0x10c5ece10). One of the two will be used. Which one is undefined.
```

Может быть, у вас есть какие-то идеи относительно того, как это победить и нормально настроить зависимости?

**Comment by bamx23** [comment]
Для решения проблемы из первого сообщения можно попробовать что-то такое:
```ruby
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```
Однако проблема дублирования в рантайме может сохраниться.
Попробуйте в Вашей кастомной спеке указать динамический фреймворк AppMetrica:
```ruby
s.dependency 'YandexMobileMetrica/Dynamic', '>= 2.6.5', '< 3.0.0'
```
И можно подробнее, как Вы собрали динамический фреймворк из статической библиотеки?

**Comment by HiveHicks** [comment]
Указание динамической версии `YandexMobileMetrica` помогло.

Фрэймворк собирал вторым методом, описанным здесь: https://pewpewthespells.com/blog/convert_static_to_dynamic.html. Любопытно, что я Яндексом это сработало, а с GoogleMobileAds — нет, все так же ругается на transitive dependencies that include static binaries.

**Comment by kanstantsin** [comment]
Вышла сборка YandexMobileAds динамическим фреймворком. Можно пробовать ```s.dependency 'YandexMobileAds/Dynamic'```. Если будут проблемы, просьба переоткрыть Issue.
