### ISSUE TITLE
Required assets "media" is not visible in ad view

### ISSUE THREAD

**Issue by sskurzhanskiy** [yandexmobile/yandex-ads-sdk-ios#47]
При показе рекламы в режиме отладки появляется вот такое предупрежение, хотя по данным которые приходят в YMANativeAdAssets media = nil

assets	YMANativeAdAssets	0x000000028085ee20
baseNSObject@0	NSObject	
_feedbackAvailable	bool	true
_age	id	0x0	0x0000000000000000
_body	__NSCFString *	"Онлайн премьера нового Audi Q7 в Ауди Центр Восток. Оставьте заявку."	0x0000000280b492c0
_callToAction	id	0x0	0x0000000000000000
_closeButton	id	0x0	0x0000000000000000
_domain	__NSCFString *	"stock.audi-vostok.ru"	0x00000002834be430
_favicon	id	0x0	0x0000000000000000
_icon	id	0x0	0x0000000000000000
_image	YMANativeAdImage?	0x00000002834b8ed0
_media	id	0x0	0x0000000000000000
_price	id	0x0	0x0000000000000000
_rating	id	0x0	0x0000000000000000
_reviewCount	id	0x0	0x0000000000000000
_sponsored	__NSCFString *	"Яндекс.Директ"	0x0000000282f91f00
_title	__NSCFString *	"Audi Q7 в Ауди Центре Восток"	0x0000000281979450
_warning	id	0x0	0x0000000000000000

При отображении другой рекламы такого же формата, но если есть warning предупреждения нет. Совпадение ?

Как понять и исправить Required assets "media" is not visible in ad view ?

**Comment by messin9** [comment]
В чем в итоге была проблема?
