### ISSUE TITLE
Просмотры не засчитываются при отображении рекламы в списках, построенных на библиотеке IGListKit

### ISSUE THREAD

**Issue by egor-bulgakov** [yandexmobile/yandex-ads-sdk-ios#51]
[IGListKit](https://github.com/Instagram/IGListKit) - open-source библиотека от Instagram для построения списков и коллекций в Swift. При интеграции Yandex Mobile Ads в список IGListKit в консоли отображается предупреждение:

`<Warning>: Impression could not be tracked. Will attempt to track impression later. Error: Ad view is not visible for required percent`

При этом реклама отображается корректно и полностью, сообщение "Ad binding successful" в логах не появляется.

Проект для воспроизведения проблемы:
[yandex-iglistkit.zip](https://github.com/yandexmobile/yandex-ads-sdk-ios/files/5014866/yandex-iglistkit.zip)

**Comment by mobile-ads-github** [comment]
Здарствуйте
Ошибка **Ad view is not visible for required percent** типична для приложений с лентой
Получить такую ошибку можно например таким образом
<img width="559" alt="image" src="https://user-images.githubusercontent.com/31896236/89196734-4adbc300-d5b3-11ea-9a46-3a279a4b83e3.png">

Но если доскролить и отобразить баннер полность, то показ будет засчитан
<img width="559" alt="image" src="https://user-images.githubusercontent.com/31896236/89196718-457e7880-d5b3-11ea-8e08-5631bea91a63.png">

Сообщение о засчитанном показе сейчас к сожалению не выводится в консоль

Насчет сообщения **Ad binding successful**, оно выводится только для нативной рекламы, а в приложение используется баннерная реклама

**Comment by egor-bulgakov** [comment]
Спасибо за информацию
