### ISSUE TITLE
Вопрос: Планируется ли сделать универсальный View/Binder для YMANativeGenericAd?

### ISSUE THREAD

**Issue by soniccat** [yandexmobile/yandex-ads-sdk-ios#55]
Привет
Я вижу в Android Yandex Ads SDK есть NativeAdViewBinder.Builder с помощью которого можно избавиться от NativeAppInstallAdView и NativeContentAdView.
В iOS есть YMANativeGenericAd но судя по примерам в репозитории, нужно все еще использовать YMANativeAppInstallAdView и YMANativeContentAdView. Планируется ли универсальный подход чтобы отказаться от конкретных view как уже сделано в Android SDK?

**Comment by mobile-ads-github** [comment]
Здравствуйте, да, планируем сделать такой подход для версии SDK 3.0.0
