### ISSUE TITLE
Не открывается YMAInterstitialAd контроллер в iOS 14

### ISSUE THREAD

**Issue by CroperMR** [yandexmobile/yandex-ads-sdk-ios#58]
В методе делегата interstitialAdDidLoad после вызова presentFromViewController ничего не происходит в iOS 14. Тот же код для iOS 12 отрабатывает без проблем.

```
- (void)interstitialAdDidLoad:(YMAInterstitialAd *)interstitialAd {
    WS(weakSelf);
    [interstitialAd presentFromViewController:self dismissalBlock:^{
        [weakSelf startApp];
    }];
}
```

**Comment by mobile-ads-github** [comment]
Здравствуйте

Возможно проблема связана с обновлением SDK на версию 3.0.0, в которой данный коллбэк был переименован.
С полным руководством по миграции на версию 3.0.0 можно ознакомиться в документации - https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/migration-guide.html/

**Comment by CroperMR** [comment]
Проблема была решена только после удаления SceneDelegate и UIApplicationSceneManifest из plist файла.
После этого на устройствах выше iOS 12 YMAInterstitialAd стал открываться.

**Comment by Str4tos** [comment]
Та же проблема.  
Если использовать **SceneDelegate** то на iOS 14 ничего не происходит при вызове показа `YMAInterstitialAd`. 
При этом не важно откуда происходит вызов.
```swift
DispatchQueue.main.async{
  self.interstitial.present(from: self)
}
```

**Comment by mobile-ads-github** [comment]
Здравствуйте.
Действительно, есть такая проблема и в новой версии. Передали разработчикам, будем исправлять.

**Comment by Str4tos** [comment]
Все еще актуальная проблема для [Yandex SDK 3.2.0](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/tag/release-3.2.0)

**Comment by mobile-ads-github** [comment]
Добрый день! Проблема будет исправлена в новых релизах

**Comment by mobile-ads-github** [comment]
Добрый день.
Проблема исправлена в версии 3.3.0.
