### ISSUE TITLE
Чёрный экран после жалобы на рекламу

### ISSUE THREAD

**Issue by aserrr** [yandexmobile/yandex-ads-sdk-ios#59]
Если во время показа YMARewardedAd кликнуть на (...) и на открывшемся экране "Пожаловаться на рекламу" указать причину, то на экране остаётся UITransitionView с YMARotatingFullscreenViewController и чёрным YMAMraidWebView внутри. При этом UI полностью блокируется.
<img width="718" alt="Снимок экрана 2020-11-03 в 12 00 30" src="https://user-images.githubusercontent.com/6837660/97966523-fff96380-1dcc-11eb-9a56-5700601bc00d.png">
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-11-03 at 11 57 51](https://user-images.githubusercontent.com/6837660/97966555-0a1b6200-1dcd-11eb-8f68-001db1b6037f.png)

**Comment by mobile-ads-github** [comment]
Спасибо, передали разработчикам сообщение об проблеме.

**Comment by mobile-ads-github** [comment]
Добрый день! Проблема была исправлена
