### ISSUE TITLE
ERROR ITMS-90535: Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by iwheelbuy** [yandexmobile/yandex-ads-sdk-ios#61]
> ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/xxx.app/YandexMobileAdsBundle.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
Return status of iTunes Transporter was 1: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/xxx.app/YandexMobileAdsBundle.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

Началось после перехода с `pod 'YandexMobileAds', '2.20.0'` на `'3.1.0'`

**Comment by mobile-ads-github** [comment]
Здравствуйте, исправили эту проблему в версии 3.1.1
