### ISSUE TITLE
Ошибка при загрузке баннера. Banner rendering failed with timeout 

### ISSUE THREAD

**Issue by CroperMR** [yandexmobile/yandex-ads-sdk-ios#63]
Подскажите пожалуйста, с чем может быть связана данная проблема?

AdFox loading error: Error Domain=com.yandex.mobile.YandexMobileAds.Internal Code=5 "Banner rendering failed with timeout" UserInfo={NSLocalizedDescription=Banner rendering failed with timeout}

**Comment by mobile-ads-github** [comment]
Здравствуйте, работаем над исправлением данной проблемы.
