### ISSUE TITLE
Strange error: "Received ad type is different from requested type"

### ISSUE THREAD

**Issue by rudensm** [yandexmobile/yandex-ads-sdk-ios#7]
Check Examples/NativeExample. I didn't get this error before.

Error Domain=com.yandex.mobile.YandexMobileAds Code=7 "Received ad type is different from requested type" UserInfo={NSLocalizedDescription=Received ad type is different from requested type}

<img width="1002" alt="2017-02-20_1524" src="https://cloud.githubusercontent.com/assets/207787/23126747/dab6ec9e-f780-11e6-98a1-9ccf492bcaa9.png">

**Comment by kanstantsin** [comment]
Thank you for report.
It's a backend bug, will be fixed soon.

**Comment by rudensm** [comment]
@kanstantsin update this thread please, when it will be fixed. Thanks.

**Comment by kanstantsin** [comment]
Fixed

**Comment by RavenEIA** [comment]
Hi!
I have the same issue with banner advertising on YandexMobileAds, version 2.7.0.

Code for requesting
```objc
self.adView = [[YMAAdView alloc] initWithBlockID:@"R-M-220025-1" adSize:[YMAAdSize fixedSizeWithCGSize:YMAAdSizeBanner_320x50] delegate:self];
[self.adView loadAd];
```
What could be the reason?

**Comment by kanstantsin** [comment]
Hi!
As far as I know the reason is the attempt to load HTML ad with block id which is configured for native ads.

**Comment by RavenEIA** [comment]
Thanks Kanstantsin! You are right.

**Comment by rustamsmax** [comment]
<img width="603" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-ios/assets/36570577/a3bea2a0-c05b-4355-9b30-8faed63112ae">

What?
