### ISSUE TITLE
Wrong 'Download latest SDK archive' link (should be 4.1.2)

### ISSUE THREAD

**Issue by Aleksey-ShmaliyViber** [yandexmobile/yandex-ads-sdk-ios#75]
README.md file contains wrong link to the latest SDK (current link is https://storage.mds.yandex.net/get-ads-mobile-sdk/205984/YandexMobileAds-4.0.0-ios-4ba3309b-e23c-4a37-9eef-b037c03a98d5.zip , but the latest version is 4.1.2).

**Comment by mobile-ads-github** [comment]
corrected
