### ISSUE TITLE
Проблемы с загрузкой СДК в странах которые блокируют yandex.net

### ISSUE THREAD

**Issue by Str4tos** [yandexmobile/yandex-ads-sdk-ios#77]
Добрый день. 
Я разработчик приложений которые монетизируются с помощью Yandex Ads во всем мире.  
Однако я нахожусь и собираю свои приложения в Украине, используя местных интернет провайдеров.  
К сожалению в моей стране `yandex.net` считается запрещенным ресурсом в интернете. 

YandexMobileAds framework хранится на `storage.mds.yandex.net` ресурсе который тоже попадает под ограничения.   
По этому когда я пытаюсь скачать framework, используя Cocoapods, у меня происходит ошибка:
```
Error installing YandexMobileAds
Transient problem: timeout
Could not resolve host: storage.mds.yandex.net
```

Могу ли я просить вас распространять YandexMobileAds SDK на других ресурсах? Например [Github Releases](https://github.com/yandexmobile/yandex-ads-sdk-ios/releases).  
Для этого достаточно прикрепить архив с SDK к релизу и указать ссылку в Podspec для новой версии в Cocoapods:
```
s.source = { 
  :http => "https://github.com/yandexmobile/yandex-ads-sdk-ios/releases/download/#{s.version}/YandexMobileAds.zip" 
}
``` 

Спасибо за понимание.

**Comment by mobile-ads-github** [comment]
Спасибо, что сообщили о такой проблеме. Мы постараемся это исправить.
