### ISSUE TITLE
YMAInterstitialController cannot be hidden programmatically

### ISSUE THREAD

**Issue by ghost** [yandexmobile/yandex-ads-sdk-ios#8]
Я использую таймер для показа YMAInterstitialController, который помещаю поверх нового создаваемого UIWindow, чтобы использовать таймер для скрытия рекламы. Будет ли возможность скрыть программно данный контроллер? Или же данная реализация не допустима.
Сейчас я имею несколько вариантов как скрыть контроллер, но в стеке Windows не удаляются  новые window и с каждым новым показом количество UIWindow в стеке увеличивается на 1

**Comment by kanstantsin** [comment]
Возможность программного скрытия полноэкранной рекламы не предусмотрена. У пользователя всегда есть возможность скрыть ее вручную. Скрытие полноэкранной рекламы программно не рекомендуется, и консистентное поведение SDK в этом случае не гарантируется.

**Comment by Appvilion** [comment]
а когда у полноэкранной рекламы появится поддержка экранов iPhone 4.7 & 5.5 ? 
В настоящий момент самый большой блок все равно мал и выглядит это не очень презентабельно.
