### ISSUE TITLE
M1 Simulator support

### ISSUE THREAD

**Issue by kubbing** [yandexmobile/yandex-ads-sdk-ios#84]
Hello, are you planning to support M1 arm simulator in the future? Right now we can't run simulator builds on M1 Macs.

Macbook Air M1, Xcode 12.5, YandexMobileAds/Dynamic (4.3.0)

<img width="1065" alt="Screenshot 2021-08-01 at 16 13 03" src="https://user-images.githubusercontent.com/324165/127997726-23c5b3ba-28d5-4b96-a3fb-5a6e32ddcbe5.png">

**Comment by mobile-ads-github** [comment]
Thank you for your report.
We plan to add support for m1 simulators no earlier than mid-September.

**Comment by temkich** [comment]
когда планируется обновление?

**Comment by mobile-ads-github** [comment]
m1 support added in release 5.0.0-alpha.1
