### ISSUE TITLE
YandexMobileAds 4.4.1 blocks the use of the new version of YandexMobileMetrica 4.0+

### ISSUE THREAD

**Issue by alexander-kurilovich-gismart** [yandexmobile/yandex-ads-sdk-ios#88]
In our project, we use our own analytical framework, one of the analytical adapters of which is `YandexMobileMetrica`. Also, our product uses one of the advertising mediation libraries, which in turn uses `YandexMobileAds`. In order to use the newer version of `YandexMobileMetrica` (4.0.0 or higher), you need to update `YandexMobileAds`, because the latest version 4.4.1 sets a hard limit in the [subspec file](https://github.com/CocoaPods/Specs/blob/fa79fb233a0393745508ae531eefc0c97e752b91/Specs/a/c/5/YandexMobileAds/4.4.1/YandexMobileAds.podspec.json) for the version of the YandexMobileMetrica library used "<4.0.0". 
```
"YandexMobileMetrica": [
          ">= 3.14.1",
          "< 4.0.0"
        ]
```
![image](https://user-images.githubusercontent.com/70638752/138069999-f26c8c13-b2f0-46d9-a138-b2bba79c19aa.png)
Any feedback and progress on this issue will be very grateful. Thank you in advance.

**Comment by mobile-ads-github** [comment]
Hi
You can use YandexMobileMetrica version 4.0.0 with YandexMobileAds version 5.0.0-alpha.2
