### ISSUE TITLE
Нет поддержки SPM

### ISSUE THREAD

**Issue by aisulubekbossynova** [yandexmobile/yandex-ads-sdk-ios#89]

**Comment by aisulubekbossynova** [comment]
Кто сталкивался с проблемой поддержки SPM? И как вы решили эту проблему?

**Comment by mobile-ads-github** [comment]
Добрый день! На данный момент Swift Package Manager не поддерживается.

**Comment by NikitaVashchenko** [comment]
Здравствуйте. Когда планируется поддержка SPM?

**Comment by druidvav** [comment]
2022 год. Пора бы уже сделать поддержку spm

**Comment by mobile-ads-github** [comment]
Добрый день, мы добавили поддержку  SPM
О том как подключить нашу библиотеку таким образом можно прочитать в [документации](https://yandex.ru/dev/mobile-ads/doc/ios/quick-start/ios-ads-component.html)

**Comment by druidvav** [comment]
Сделали, но недоделали. А медиацию кто в spm делать будет? Библиотеки гугла уже доступны там.
