### ISSUE TITLE
Ошибка Ad request failed with network error

### ISSUE THREAD

**Issue by ancloid** [yandexmobile/yandex-ads-sdk-ios#97]
Для rewarded video получаю ошибку даже на тестовом блоке @"R-M-DEMO-rewarded-client-side-rtb"
Что это значит? Или просто нет рекламы для этого региона?

Error Domain=com.yandex.mobile.YandexMobileAds Code=4 "Ad request failed with network error" UserInfo={NSLocalizedDescription=Ad request failed with network error, NSUnderlyingError=0x281569920 {Error Domain=com.yandex.mobile.YandexMobileAds Code=4 "Incorrect data in server response" UserInfo={NSLocalizedDescription=Incorrect data in server response, NSLocalizedFailureReason=Expected array, got: (
)}}}

**Comment by mobile-ads-github** [comment]
Работа блока уже исправлена
