### ISSUE TITLE
Crash  с причиной '[UIScreen yma_size]: unrecognized selector sent to instance ...'

### ISSUE THREAD

**Issue by moslienko** [yandexmobile/yandex-ads-sdk-ios#98]
После обновления библиотеки до версии 5.0 приложение стало вылетать, причина на скриншоте. Происходит после создания объекта рекламы, причем не важно что я пытаюсь загрузить - баннер, или рекламу с вознаграждением.
` self.rewardedAd = YMARewardedAd(adUnitID: ...)`. 
  Использую библиотеки след.версий:
 ```
  pod 'YandexMobileMetrica/Dynamic', '4.2.0'
  pod 'YandexMobileAds/Dynamic', '5.0.0'
  pod 'AdMobYandexMobileAdsAdapters/Dynamic', '9.0.0.0'
  pod 'FacebookYandexMobileAdsAdapters/Dynamic', '6.9.0.0'
  pod 'UnityAdsYandexMobileAdsAdapters/Dynamic', '4.0.0.0'
```

![Снимок экрана 2022-04-01 в 16 02 20](https://user-images.githubusercontent.com/8676976/161231668-04c03d55-f19e-47ca-9249-2bb1299570d2.png)
.

**Comment by mobile-ads-github** [comment]
Здравствуйте

Подскажите, пожалуйста, включены ли у вас в проекте флаги ```-ObjC -all_load```, не изменяете ли вы значение ```OTHER_LDFLAGS```, которое выставляет cocoapods?

Также, мы рекомендуем использовать static версию

**Comment by moslienko** [comment]
Static заработали, спасибо.
Да,  такие флаги есть, + по моему что-то менял что бы какая-то другая либа завелась.
