### ISSUE TITLE
dSYM teamcity .pcm

### ISSUE THREAD

**Issue by aserrr** [yandexmobile/yandex-ads-sdk-ios#99]
При сборке проекта в релизной конфигурации (с dSYM), много вот таких ворнингов в логе:

(arm64)  could not find object file symbol for symbol _$sSo16UIViewControllerC14CommonCoreTinyE9showAlertyyAC0G5ModelVF
(arm64)  could not find object file symbol for symbol _$sSo17UIAlertControllerCML

/Users/teamcity/buildAgent/work/c7c4b5d20e671c26/YandexMobileAds/DerivedData-iphonesimulator/ModuleCache.noindex/Q2ON55N5OAE2/TemplatesSupport-20J3ZMVW3JJ64.pcm: No such file or directory
/Users/teamcity/buildAgent/work/c7c4b5d20e671c26/YandexMobileAds/DerivedData-iphonesimulator/ModuleCache.noindex/Q2ON55N5OAE2/CoreFoundation-1I3ZUZGX3ZAWD.pcm: No such file or directory

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за информацию, работаем над устранением проблемы.

**Comment by kattouf** [comment]
Привет! Столкнулись с такой же проблемой при интеграции, есть какие-нибудь апдейты по решению?

**Comment by SanatzhanAimukambetov** [comment]
Привет! Уже прошло больше 7 месяцев) Есть какие-нибудь апдейты?

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!
